
import { Localized, LocalizedAttributes } from "../../../../components/localized";
import Link from 'next/link';
import { apiGet } from '../../../../lib/api';
import type { Context, Execution, ReleaseOption } from '../../../../lib/dvp-types';

type Profile = { id: string; item_no: string; title: string; scope: string; status: string; plan: { plan_no: string; title: string; change_request_no: string | null } | null; release_options: ReleaseOption[]; release_options_truncated: boolean; linked_acceptance: { id: string; criterion_no: string; description: string }[]; linked_change_points: { id: string; change_no: string; title: string }[]; linked_issues: { issue_no: string; title: string }[] };
type History = { context: Context; total: number; items: Execution[]; next_before_number: number | null };

export default async function Page({ params, searchParams }: { params: Promise<{ itemId: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const { itemId } = await params; const filters = await searchParams;
  const query = new URLSearchParams(); for (const key of ['release_id', 'snapshot_no', 'result', 'before_number']) if (filters[key]) query.set(key, filters[key]!);
  const path = `/api/v1/testing/dvp/id/${encodeURIComponent(itemId)}`;
  const [item, history] = await Promise.all([apiGet<Profile>(`${path}/profile`), apiGet<History>(`${path}/executions?${query}`)]);
  if (!item) return <section className="panel"><h1><Localized>{"DVP item unavailable"}</Localized></h1><p className="muted"><Localized>{"The item was not found or the API is unavailable."}</Localized></p><Link href="/testing/dvp"><Localized>{"All DVP items →"}</Localized></Link></section>;
  const next = new URLSearchParams(query); if (history?.next_before_number) next.set('before_number', String(history.next_before_number));
  const first = new URLSearchParams(query); first.delete('before_number');
  return <>
    <p><Link href={`/resources?entity_type=DVP_ITEM&entity_id=${item.id}`}><Localized>{"Materials & evidence references →"}</Localized></Link></p>
    <div className="top"><div><div className="eyebrow"><Localized>{"DVP TEST ITEM · "}</Localized><Localized>{item.item_no}</Localized></div><h1><Localized>{item.title}</Localized></h1><p className="muted"><Localized>{item.scope}</Localized><Localized>{" · "}</Localized><Localized>{item.plan?.plan_no || 'No plan'}</Localized></p></div><span className="status"><Localized>{item.status}</Localized></span></div>
    <section className="panel"><h2><Localized>{"Verification assignments"}</Localized></h2><Localized>{item.plan?.change_request_no && <p><Link href={`/changes/${encodeURIComponent(item.plan.change_request_no)}`}><Localized>{item.plan.change_request_no}</Localized></Link><Localized>{" · "}</Localized><Link href={`/changes/${encodeURIComponent(item.plan.change_request_no)}/coverage`}><Localized>{"Coverage review →"}</Localized></Link></p>}</Localized><p><Localized>{"Acceptance: "}</Localized><Localized>{item.linked_acceptance.map(a => `${a.criterion_no}: ${a.description}`).join('; ') || 'No acceptance assignment recorded'}</Localized></p><p><Localized>{"Change points: "}</Localized><Localized>{item.linked_change_points.map(p => `${p.change_no}: ${p.title}`).join('; ') || 'No change point assignment recorded'}</Localized></p><p><Localized>{"Issues: "}</Localized><Localized>{item.linked_issues.length ? item.linked_issues.map(i => <span key={i.issue_no}><Link href={`/issues/${encodeURIComponent(i.issue_no)}`}><Localized>{"#"}</Localized><Localized>{i.issue_no}</Localized><Localized>{" · "}</Localized><Localized>{i.title}</Localized></Link> </span>) : 'No issue assignment recorded'}</Localized></p></section>
    <section className="panel"><form method="get" className="filters"><label><Localized>{"Release "}</Localized><select name="release_id" defaultValue={filters.release_id || ''}><option value=""><Localized>{"All recorded contexts"}</Localized></option><Localized>{filters.release_id && !item.release_options.some(r => r.id === filters.release_id) && <option value={filters.release_id}><Localized>{history?.context.release?.version || 'Selected release'}</Localized></option>}</Localized><Localized>{item.release_options.map(r => <option key={r.id} value={r.id}><Localized>{r.type === 'APPLICATION' ? 'ASR' : 'SSR'}</Localized> <Localized>{r.version}</Localized></option>)}</Localized></select></label><label><Localized>{"Historical snapshot "}</Localized><LocalizedAttributes><input name="snapshot_no" defaultValue={filters.snapshot_no || ''} placeholder="Latest frozen snapshot" maxLength={80} /></LocalizedAttributes></label><label><Localized>{"Result "}</Localized><LocalizedAttributes><input name="result" defaultValue={filters.result || ''} placeholder="PASS / FAIL" maxLength={30} /></LocalizedAttributes></label><button type="submit"><Localized>{"Filter history"}</Localized></button><Link href={`/testing/dvp/${itemId}`}><Localized>{"Reset"}</Localized></Link></form><p className="muted"><Localized>{"Selecting a release uses its latest frozen snapshot unless a historical snapshot is supplied. Every row retains its recorded context. Declared item status is separate from execution evidence."}</Localized></p><Localized>{item.release_options_truncated && <p className="muted"><Localized>{"The selector shows the first 100 recorded releases."}</Localized></p>}</Localized></section>
    <Localized>{history ? <section className="panel tablewrap"><h2><Localized>{"Execution history ("}</Localized><Localized>{history.total}</Localized><Localized>{")"}</Localized></h2><p className="muted"><Localized>{history.context.snapshot ? `Exact context: ${history.context.snapshot.snapshot_no}` : history.context.release ? 'No frozen snapshot for selected release.' : 'All recorded releases and snapshots.'}</Localized><Localized>{" Newest execution first; an earlier PASS does not verify a later snapshot."}</Localized></p><table><thead><tr><th><Localized>{"Execution / Result"}</Localized></th><th><Localized>{"Release"}</Localized></th><th><Localized>{"Snapshot"}</Localized></th><th><Localized>{"Test Release"}</Localized></th><th><Localized>{"Time / Observation"}</Localized></th></tr></thead><tbody><Localized>{history.items.map(e => <tr key={e.execution_no}><td><Localized>{"#"}</Localized><Localized>{e.execution_no}</Localized><Localized>{" · "}</Localized><span className={'status ' + (e.result === 'PASS' && e.context_consistent ? 'pass' : 'warning')}><Localized>{e.result}</Localized></span><Localized>{!e.context_consistent && <p className="muted"><Localized>{"Context mismatch; review record"}</Localized></p>}</Localized></td><td><Link href={`/releases/${e.release_type === 'APPLICATION' ? 'application' : 'standard'}/${e.release_id}`}><Localized>{e.release_type === 'APPLICATION' ? 'ASR' : 'SSR'}</Localized> <Localized>{e.release_version || e.release_id}</Localized></Link></td><td><Localized>{e.snapshot_no ? <Link href={`/snapshots/${encodeURIComponent(e.snapshot_no)}`}><Localized>{e.snapshot_no}</Localized></Link> : e.snapshot_id}</Localized></td><td><Localized>{e.test_release_no ? <Link href={`/testing/releases/${encodeURIComponent(e.test_release_no)}`}><Localized>{e.test_release_no}</Localized></Link> : '—'}</Localized></td><td><Localized>{e.executed_at}</Localized><div><Localized>{e.actual_result || '—'}</Localized></div></td></tr>)}</Localized></tbody></table><Localized>{!history.items.length && <p className="muted"><Localized>{"No matching executions recorded."}</Localized></p>}</Localized><p><Localized>{filters.before_number && <Link href={`/testing/dvp/${itemId}?${first}`}><Localized>{"Newest page"}</Localized></Link>}</Localized><Localized>{history.next_before_number !== null && <Link href={`/testing/dvp/${itemId}?${next}`}><Localized>{" Earlier executions →"}</Localized></Link>}</Localized></p></section> : <section className="panel"><h2><Localized>{"History unavailable"}</Localized></h2><p className="muted"><Localized>{"Check the release/snapshot filters or API availability."}</Localized></p></section>}</Localized>
    <p><Link href="/testing/dvp"><Localized>{"All DVP items →"}</Localized></Link></p>
  </>;
}
