import Link from 'next/link';
import { apiGet } from '../../../lib/api';

type IssueDetail={id:string;issue_no:string;title:string;scope:string;severity:string;status:string;description?:string|null;change_requests:{request_no:string;title:string;status:string;relation_type:string}[]};
const fallback:IssueDetail={id:'1',issue_no:'310',title:'Low-temperature charging timeout',scope:'STANDARD',severity:'HIGH',status:'FIX_VERIFIED',description:'Charging timeout observed under low-temperature conditions.',change_requests:[{request_no:'SCR-142',title:'Charging timeout & low-temperature calibration',status:'IN_TEST',relation_type:'FIXED_BY'}]};
export default async function Page({params}:{params:Promise<{id:string}>}){
 const {id}=await params;
 const apiData=await apiGet<IssueDetail>('/api/v1/issues/'+id);
 const issue=apiData||fallback;
 return <><div className="top"><div><div className="eyebrow">ISSUE #{issue.issue_no} · {issue.scope}</div><h1>{issue.title}</h1><p className="muted">Severity {issue.severity} · {issue.description}</p></div><span className="status pass">{issue.status.replaceAll('_',' ')}</span></div><div className="grid2"><section className="panel"><h2>Issue assessment</h2><div className="kv"><span>Scope</span><b>{issue.scope}</b><span>Severity</span><b>{issue.severity}</b><span>Status</span><b>{issue.status}</b><span>Fix request</span>{issue.change_requests[0]?<Link href={'/changes/'+issue.change_requests[0].request_no}><b>{issue.change_requests[0].request_no}</b></Link>:<b>—</b>}</div></section><section className="panel"><h2>Impact Path</h2><div className="impactpath"><b>Standard Software</b><i>→</i><b>Application Release</b><i>→</i><b>Customer / Project</b><i>→</i><b>Deployment / Batch</b></div></section></div><section className="panel"><h2>Linked change requests</h2><table><thead><tr><th>SCR</th><th>Title</th><th>Relation</th><th>Status</th></tr></thead><tbody>{issue.change_requests.map(r=><tr key={r.request_no}><td><Link href={'/changes/'+r.request_no}><b>{r.request_no}</b></Link></td><td>{r.title}</td><td>{r.relation_type}</td><td>{r.status}</td></tr>)}</tbody></table></section>{!apiData&&<p className="datasource">Demo fallback active.</p>}</>
}