
import { Localized, LocalizedAttributes } from "../../../components/localized";
import Link from 'next/link';
import { apiGet } from '../../../lib/api';

type IssueDetail = { id: string; issue_no: string; title: string; scope: string; severity: string; status: string; description: string | null; change_requests: { request_no: string; title: string; status: string; relation_type: string }[] };
type Impact = { issue_no: string; linked_changes: { request_no: string; title: string; status: string; relation_type: string }[]; candidate_releases: { id: string; release_type: string; version: string; status: string; software: { code: string; name: string }; customer: string | null; project: string | null; customer_code: string | null; project_id: string | null; deployment_count: number; batch_count: number; snapshot: { snapshot_no: string } | null; assessment: { decision: string } | null }[]; truncated: boolean; basis: string };

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const path = `/api/v1/issues/${encodeURIComponent(id)}`;
  const [issue, impact, history] = await Promise.all([apiGet<IssueDetail>(path), apiGet<Impact>(`${path}/impact`), apiGet<{ items: { id: string; release_id: string; release_version: string; snapshot_no: string; decision: string; reason: string; actor_name: string; created_at: string }[]; truncated: boolean }>(`${path}/impact-assessments`)]);
  if (!issue) return <section className="panel"><h1><Localized>{"Issue unavailable"}</Localized></h1><p className="muted"><Localized>{"The issue was not found or the API could not be reached."}</Localized></p><Link href="/issues"><Localized>{"Back to issues →"}</Localized></Link></section>;
  return <>
    <p><Link href={`/resources?entity_type=ISSUE&entity_id=${issue.id}`}><Localized>{"Materials & evidence references →"}</Localized></Link></p>
    <div className="top"><div><div className="eyebrow"><Localized>{"ISSUE #"}</Localized><Localized>{issue.issue_no}</Localized><Localized>{" · "}</Localized><Localized>{issue.scope}</Localized></div><h1><Localized>{issue.title}</Localized></h1><p className="muted"><Localized>{"Severity "}</Localized><Localized>{issue.severity}</Localized><Localized>{" · "}</Localized><Localized>{issue.description || 'No description recorded.'}</Localized></p></div><span className={'status ' + (issue.status.includes('VERIFIED') || issue.status === 'CLOSED' ? 'pass' : 'warning')}><Localized>{issue.status.replaceAll('_', ' ')}</Localized></span></div>
    <div className="grid2"><section className="panel"><h2><Localized>{"Issue assessment"}</Localized></h2><div className="kv"><span><Localized>{"Scope"}</Localized></span><b><Localized>{issue.scope}</Localized></b><span><Localized>{"Severity"}</Localized></span><b><Localized>{issue.severity}</Localized></b><span><Localized>{"Status"}</Localized></span><b><Localized>{issue.status}</Localized></b><span><Localized>{"Linked SCR"}</Localized></span><b><Localized>{issue.change_requests.length}</Localized></b></div></section><section className="panel"><h2><Localized>{"Version review"}</Localized></h2><Localized>{impact ? <><p><b><Localized>{impact.candidate_releases.length}</Localized></b><Localized>{" candidate software release(s)"}</Localized></p><p className="muted"><Localized>{impact.basis}</Localized></p><Localized>{impact.truncated && <p className="muted"><Localized>{"Only the first 200 matching releases are shown."}</Localized></p>}</Localized></> : <p className="muted"><Localized>{"Impact API unavailable."}</Localized></p>}</Localized></section></div>
    <section className="panel tablewrap"><h2><Localized>{"Linked change requests"}</Localized></h2><table><thead><tr><th><Localized>{"SCR"}</Localized></th><th><Localized>{"Title"}</Localized></th><th><Localized>{"Relation"}</Localized></th><th><Localized>{"Status"}</Localized></th></tr></thead><tbody><Localized>{issue.change_requests.map(row => <tr key={row.request_no}><td><Link href={`/changes/${encodeURIComponent(row.request_no)}`}><b><Localized>{row.request_no}</Localized></b></Link></td><td><Localized>{row.title}</Localized></td><td><Localized>{row.relation_type}</Localized></td><td><Localized>{row.status}</Localized></td></tr>)}</Localized></tbody></table><Localized>{issue.change_requests.length === 0 && <p className="muted"><Localized>{"No SCR linked to this issue."}</Localized></p>}</Localized></section>
    <Localized>{impact && <section className="panel tablewrap"><h2><Localized>{"Candidate releases for impact review"}</Localized></h2><table><thead><tr><th><Localized>{"Release"}</Localized></th><th><Localized>{"Software"}</Localized></th><th><Localized>{"Customer / Project"}</Localized></th><th><Localized>{"Status"}</Localized></th><th><Localized>{"Snapshot / Judgment"}</Localized></th><th><Localized>{"Actual Deployments"}</Localized></th><th><Localized>{"Production Batches"}</Localized></th></tr></thead><tbody><Localized>{impact.candidate_releases.map(row => <tr key={row.id}><td><Localized>{row.release_type === 'APPLICATION' ? <Link href={`/releases/application/${row.id}`}><b><Localized>{"ASR "}</Localized><Localized>{row.version}</Localized></b></Link> : <Link href={`/releases/standard/${row.id}`}><b><Localized>{"SSR "}</Localized><Localized>{row.version}</Localized></b></Link>}</Localized></td><td><Localized>{row.software.name}</Localized><Localized>{" · "}</Localized><Localized>{row.software.code}</Localized></td><td><Localized>{row.customer_code ? <Link href={`/customers/${encodeURIComponent(row.customer_code)}`}><Localized>{row.customer}</Localized></Link> : '—'}</Localized><Localized>{" / "}</Localized><Localized>{row.project_id ? <Link href={`/projects/${row.project_id}`}><Localized>{row.project}</Localized></Link> : '—'}</Localized></td><td><Localized>{row.status}</Localized></td><td><Link href={`/issues/${encodeURIComponent(id)}/impact/${row.id}`}><Localized>{row.snapshot?.snapshot_no || 'No snapshot'}</Localized><Localized>{" · "}</Localized><Localized>{row.assessment?.decision.replaceAll('_', ' ') || 'Needs judgment'}</Localized></Link></td><td><Localized>{row.deployment_count}</Localized></td><td><Localized>{row.batch_count}</Localized></td></tr>)}</Localized></tbody></table><Localized>{impact.candidate_releases.length === 0 && <p className="muted"><Localized>{"No candidate releases found from linked SCR software."}</Localized></p>}</Localized></section>}</Localized>
    <section className="panel tablewrap"><h2><Localized>{"Manual judgment history"}</Localized></h2><Localized>{history ? <><table><thead><tr><th><Localized>{"Release / Snapshot"}</Localized></th><th><Localized>{"Judgment / record UUID"}</Localized></th><th><Localized>{"Reason"}</Localized></th><th><Localized>{"Declared reviewer"}</Localized></th><th><Localized>{"Time"}</Localized></th></tr></thead><tbody><Localized>{history.items.map(row => <tr key={row.id}><td><Link href={`/snapshots/${encodeURIComponent(row.snapshot_no)}`}><Localized>{row.release_version}</Localized><Localized>{" / "}</Localized><Localized>{row.snapshot_no}</Localized></Link></td><td><Localized>{row.decision.replaceAll('_', ' ')}</Localized><p><code>{row.id}</code></p></td><td><Localized>{row.reason}</Localized></td><td><Localized>{row.actor_name}</Localized></td><td><Localized>{row.created_at}</Localized></td></tr>)}</Localized></tbody></table><Localized>{history.items.length === 0 && <p className="muted"><Localized>{"No judgments recorded. Candidates have not been confirmed as affected."}</Localized></p>}</Localized><Localized>{history.truncated && <p className="muted"><Localized>{"Showing the latest 50 judgments. The history API supports up to 200."}</Localized></p>}</Localized></> : <p className="muted"><Localized>{"Judgment history API unavailable."}</Localized></p>}</Localized></section>
  </>;
}
