import Link from 'next/link';
import { apiGet } from '../lib/api';
import type { GovernanceRow } from '../lib/governance';
type Kind = 'approvals' | 'decisions';
type Catalog = { total: number; state_counts: Record<string,number>; next_offset: number | null; items: GovernanceRow[] };
export default async function GovernanceCatalog({kind,filters}:{kind:Kind;filters:Record<string,string|undefined>}) {
  const query=new URLSearchParams();for(const key of ['state','release_id','snapshot_id','approval_id','q','limit','offset'])if(filters[key])query.set(key,filters[key]!);
  const data=await apiGet<Catalog>(`/api/v1/governance/${kind}?${query}`);const path=kind==='approvals'?'/approvals':'/release-decisions';
  const first=new URLSearchParams(query);first.delete('offset');const next=new URLSearchParams(query);if(data?.next_offset!==null && data?.next_offset!==undefined)next.set('offset',String(data.next_offset));
  return <><div className="top"><div><div className="eyebrow">GOVERNANCE HISTORY</div><h1>{kind==='approvals'?'Approvals':'Release Decisions'}</h1><p className="muted">Original records and exact frozen targets. A directory status is not permission to deliver or produce.</p></div></div><p><Link href={kind==='approvals'?'/release-decisions':'/approvals'}>{kind==='approvals'?'Release decisions':'Approvals'} →</Link></p><section className="panel"><form method="get" className="filters"><label>{kind==='approvals'?'Status':'Decision'} <input name="state" defaultValue={filters.state||''} maxLength={30}/></label><label>Search <input name="q" defaultValue={filters.q||''} maxLength={200} placeholder="Record, declared actor, version or snapshot"/></label>{['release_id','snapshot_id','approval_id','limit'].filter(k=>filters[k]).map(k=><input type="hidden" key={k} name={k} value={filters[k]}/>)}<button type="submit">Filter</button><Link href={path}>Reset</Link></form>{['release_id','snapshot_id','approval_id'].filter(k=>filters[k]).map(k=><p key={k} className="muted">{k}: {filters[k]}</p>)}</section>
    {data?<section className="panel tablewrap"><h2>{data.total} matching records</h2><p className="muted">{Object.entries(data.state_counts).map(([s,n])=>`${s}: ${n}`).join(' · ')||'No state records'} · Counts cover all filtered records.</p><table><thead><tr><th>Record</th><th>Exact release / snapshot</th><th>State / binding</th><th>{kind==='approvals'?'Steps / actions / decisions':'Readiness / declared actor / time'}</th></tr></thead><tbody>{data.items.map(row=><tr key={row.id}><td><Link href={`${path}/${encodeURIComponent((row.approval_no||row.decision_no)!)}`}>{row.approval_no||row.decision_no}</Link>{row.approval&&<div><Link href={`/approvals/${encodeURIComponent(row.approval.approval_no)}`}>{row.approval.approval_no}</Link></div>}</td><td>{row.release?<Link href={`/releases/${row.release.type==='APPLICATION'?'application':'standard'}/${row.release.id}`}>{row.release.type==='APPLICATION'?'ASR':'SSR'} {row.release.version}</Link>:row.target_type==='RELEASE'?'Release missing':row.target_type||'Release missing'}<div>{row.snapshot?<Link href={`/snapshots/${encodeURIComponent(row.snapshot.snapshot_no)}`}>{row.snapshot.snapshot_no}</Link>:'Snapshot missing'}</div></td><td>{row.status||row.decision}{row.binding_state && row.binding_state!=='CONSISTENT'&&<p className="muted">{row.binding_state}</p>}{row.context_consistent===false&&<p className="muted">Recorded binding mismatch; review required</p>}</td><td>{kind==='approvals'?<>{row.step_count} steps · {row.action_count} actions · {row.decision_count} decisions<div>{row.submitted_by||'No submitter recorded'}</div></>:<>{row.readiness_status}<div>{row.decided_by}</div><div>{row.decided_at}</div></>}</td></tr>)}</tbody></table>{!data.items.length&&<p className="muted">No matching records.</p>}<p>{filters.offset&&<Link href={`${path}?${first}`}>First page</Link>}{data.next_offset!==null&&<Link href={`${path}?${next}`}> Next page →</Link>}</p></section>:<section className="panel"><h2>Governance catalog unavailable</h2><p className="muted">The API is unavailable or a filter is invalid.</p></section>}
  </>;
}
