import Link from 'next/link';
import { Localized } from './localized';
import { apiGet } from '../lib/api';
import { rawIssue,type IssueSummary,type ImpactSummary,type IssueSearch,type IssuePage } from '../lib/issue-views';
type Kind='changes'|'candidates'|'assessments'|'components'|'verification';
const offsets:Record<Kind,string>={changes:'changes_offset',candidates:'candidates_offset',assessments:'assessments_offset',components:'components_offset',verification:'verification_offset'};
const titles:Record<Kind,string>={changes:'Linked change requests',candidates:'Candidate releases for impact review',assessments:'Manual judgment history',components:'Frozen component evidence',verification:'Linked DVP verification'};
export default async function IssueCollections({data,search}:{data:IssueSummary|ImpactSummary;search:IssueSearch}) {
  const impact='issue_id' in data;
  const identifier=impact?data.issue_id:data.id;
  const route=`/issues/${encodeURIComponent(data.issue_no)}${impact?`/impact/${data.release_id}`:''}`;
  const api=`/api/v1/issue-views/${encodeURIComponent(data.issue_no)}${impact?`/impact/${data.release_id}`:''}`;
  const query=new URLSearchParams();if(impact)query.set('snapshot_id',data.snapshot_id);
  for(const key of ['issue_limit',...Object.values(offsets)]){const value=rawIssue(search,key);if(value!==undefined)query.set(key,value);}
  const href=(key:string,value?:string)=>{const q=new URLSearchParams(query);if(value===undefined)q.delete(key);else q.set(key,value);return `${route}?${q}`;};
  const kinds:Kind[]=impact?['components','verification']:['changes','candidates','assessments'];
  const counts:Partial<Record<Kind,number>>=impact?{components:data.component_count,verification:data.verification_count}:{changes:data.linked_count,candidates:data.candidate_count,assessments:data.assessment_count};
  const pages=await Promise.all(kinds.map(async kind=>{
    const params=new URLSearchParams({issue_id:identifier,limit:rawIssue(search,'issue_limit')??'50',offset:rawIssue(search,offsets[kind])??'0'});if(impact)params.set('snapshot_id',data.snapshot_id);
    const result=await apiGet<IssuePage>(`${api}/${kind}?${params}`);
    return result&&result.issue_id===identifier&&result.issue_no===data.issue_no&&(!impact||(result.release_id===data.release_id&&result.snapshot_id===data.snapshot_id))?result:null;
  }));
  return <Localized>{kinds.map((kind,index)=>{const page=pages[index];return <section className="panel tablewrap" key={kind}><h2><Localized>{titles[kind]}</Localized></h2><p><Localized>{'Complete count'}</Localized>: {counts[kind]} · <Localized>{'Records on this page'}</Localized>: {page?page.items.length:'—'}</p>
    {page?<><table><thead><tr><th><Localized>{'Reference'}</Localized></th><th><Localized>{'Description'}</Localized></th><th><Localized>{'Status / Evidence'}</Localized></th><th><Localized>{'Review'}</Localized></th></tr></thead><tbody>{page.items.map(row=><tr key={row.relation_id||row.id||`${row.code}:${row.version}`}>
      {kind==='changes'?<><td><Link href={`/changes/${encodeURIComponent(row.request_no!)}`}>{row.request_no}</Link></td><td><Localized>{row.title}</Localized></td><td><Localized>{row.status}</Localized></td><td><Localized>{row.relation_type}</Localized></td></>:kind==='candidates'?<><td><Link href={`/releases/${row.release_type==='APPLICATION'?'application':'standard'}/${row.id}`}>{row.release_type==='APPLICATION'?'ASR':'SSR'} {row.version}</Link><p><code>{row.id}</code></p></td><td><Localized>{`${row.software_name} · ${row.software_code}`}</Localized><p>{row.customer_code?<Link href={`/customers/${encodeURIComponent(row.customer_code)}`}>{row.customer}</Link>:'—'} / {row.project_id?<Link href={`/projects/${row.project_id}`}>{row.project||row.project_id}</Link>:'—'}</p></td><td><Localized>{row.status}</Localized><p><Localized>{'Actual Deployments'}</Localized>: {row.deployment_count} · <Localized>{'Production Batches'}</Localized>: {row.batch_count}</p></td><td><Link href={`/issues/${encodeURIComponent(data.issue_no)}/impact/${row.id}?${new URLSearchParams({snapshot_id:row.snapshot_id||'none'})}`}><Localized>{row.snapshot_no||'No snapshot'}</Localized> · <Localized>{row.decision?.replaceAll('_',' ')||'Needs judgment'}</Localized></Link></td></>:kind==='assessments'?<><td>{row.release_version||row.release_id}<p>{row.snapshot_no?<Link href={`/snapshots/${encodeURIComponent(row.snapshot_no)}`}>{row.snapshot_no}</Link>:<code>{row.snapshot_id}</code>}</p></td><td><Localized>{row.reason}</Localized><p><Localized>{'Evidence reference: '}</Localized><Localized>{row.evidence_ref||'Not supplied'}</Localized></p><p><code>{row.id}</code></p></td><td><Localized>{row.decision?.replaceAll('_',' ')}</Localized><p><Localized>{'Declared reviewer'}</Localized>: {row.actor_name} · {row.created_at}</p></td><td><Link href={`/issues/${encodeURIComponent(data.issue_no)}/impact/${row.release_id}?${new URLSearchParams({snapshot_id:row.snapshot_id!})}`}><Localized>{'Review recorded snapshot →'}</Localized></Link></td></>:kind==='components'?<><td>{row.code}</td><td>{row.version||<Localized>{'Version not recorded'}</Localized>}</td><td>—</td><td>—</td></>:<><td><Link href={`/testing/dvp/${row.id}`}>{row.item_no}</Link><p><code>{row.id}</code></p></td><td><Localized>{row.title}</Localized></td><td>{row.execution_no!==null&&row.execution_no!==undefined?<>#{row.execution_no} · <Localized>{row.result}</Localized><p>{row.executed_at}</p></>:<Localized>{'No matching execution'}</Localized>}</td><td><Localized>{row.actual_result||'—'}</Localized></td></>}
    </tr>)}</tbody></table>{!page.items.length&&<p><Localized>{'No records on this page.'}</Localized></p>}<p><Link href={href(offsets[kind])}><Localized>{'First page'}</Localized></Link> {page.next_offset!==null&&<Link href={href(offsets[kind],String(page.next_offset))}><Localized>{'Next page →'}</Localized></Link>}</p></>:<p><Localized>{'Issue collection page unavailable.'}</Localized></p>}
  </section>;})}</Localized>;
}
