import Link from 'next/link';
import { apiGet } from '../lib/api';
type Software = { release_id: string | null; version: string | null; type: string | null; snapshot_id: string | null; snapshot_no: string | null };
type Kind = 'deployments' | 'changeovers' | 'batches';
type Row = { id: string; record_no: string; status: string; context_consistent: boolean; binding_flags: string[]; deployment: { id: string; deployment_no: string; status: string } | null; authorization: { id: string; authorization_no: string; status: string } | null; customer: { id: string; code: string } | null; project: { id: string; code: string } | null; site: { site_code: string } | null; line: { line_code: string } | null; expected: Software | null; actual: Software | null; recorded: Software | null; from_release: Software | null; software_observation: string; changeover: { changeover_no: string; status: string } | null; changeover_linked: boolean | null; changeover_count: number | null; batch_count: number | null; recorded_at: string | null };
type Catalog = { total: number; status_counts: Record<string,number>; items: Row[]; next_offset: number | null; notice: string };
const paths = { deployments: '/deployments', changeovers: '/production/changeovers', batches: '/production/batches' };
const titles = { deployments: 'Deployments', changeovers: 'Software Changeovers', batches: 'Production Batches' };
function software(row: Software | null) { return row ? <>{row.release_id && row.version ? <Link href={`/releases/${row.type === 'APPLICATION' ? 'application' : 'standard'}/${row.release_id}`}>{row.type === 'APPLICATION' ? 'ASR' : 'SSR'} {row.version}</Link> : 'Release not resolved'}<div>{row.snapshot_no ? <Link href={`/snapshots/${encodeURIComponent(row.snapshot_no)}`}>{row.snapshot_no}</Link> : row.snapshot_id ? 'Snapshot not resolved' : 'No snapshot recorded'}</div></> : 'Not recorded'; }
export default async function ProductionCatalog({ kind, filters }: { kind: Kind; filters: Record<string,string | undefined> }) {
  const query=new URLSearchParams();
  for (const key of ['status','q','site_code','line_code','release_id','snapshot_id','authorization_id','deployment_id','customer_id','project_id','limit','offset']) if (filters[key]) query.set(key,filters[key]!);
  const data=await apiGet<Catalog>(`/api/v1/production/catalog/${kind}?${query}`);
  const first=new URLSearchParams(query);first.delete('offset');const next=new URLSearchParams(query);if(data?.next_offset !== null && data?.next_offset !== undefined)next.set('offset',String(data.next_offset));
  const scopes=['release_id','snapshot_id','authorization_id','deployment_id','customer_id','project_id','limit'];
  return <><div className="top"><div><div className="eyebrow">PRODUCTION TRACEABILITY</div><h1>{titles[kind]}</h1><p className="muted">Recorded history and exact software bindings. Matching observations do not authorize production actions.</p></div></div><p>{(Object.keys(paths) as Kind[]).filter(k=>k!==kind).map(k=><span key={k}><Link href={paths[k]}>{titles[k]} →</Link> · </span>)}</p>
    <section className="panel"><form method="get" className="filters"><label>Status <input name="status" defaultValue={filters.status || ''} maxLength={30}/></label><label>Site <input name="site_code" defaultValue={filters.site_code || ''} maxLength={80}/></label><label>Line <input name="line_code" defaultValue={filters.line_code || ''} maxLength={80}/></label><label>Search <input name="q" defaultValue={filters.q || ''} maxLength={200} placeholder="Record, authorization, version or snapshot"/></label>{scopes.filter(k=>filters[k]).map(k=><input key={k} type="hidden" name={k} value={filters[k]}/>)}<button type="submit">Filter</button><Link href={paths[kind]}>Reset</Link></form>{scopes.filter(k=>filters[k] && k!=='limit').map(k=><p className="muted" key={k}>{k}: {filters[k]}</p>)}</section>
    {data ? <section className="panel tablewrap"><h2>{data.total} matching records</h2><p className="muted">{Object.entries(data.status_counts).map(([s,n])=>`${s}: ${n}`).join(' · ') || 'No status records'} · Counts cover all filtered records.</p><p className="muted">{data.notice}</p><table><thead><tr><th>Record / trace</th><th>Customer / project / location</th><th>{kind==='deployments' ? 'Expected software' : kind==='changeovers' ? 'From → to release' : 'Batch software'}</th><th>Actual deployment software</th><th>Status / observations</th></tr></thead><tbody>{data.items.map(row=><tr key={row.id}><td>{kind==='changeovers' ? <b>{row.record_no}</b> : <Link href={`${paths[kind]}/${encodeURIComponent(row.record_no)}`}>{row.record_no}</Link>}{row.deployment && kind!=='deployments' && <div><Link href={`/deployments/${encodeURIComponent(row.deployment.deployment_no)}`}>{row.deployment.deployment_no}</Link></div>}{row.authorization && <div><Link href={`/distribution/authorizations/${encodeURIComponent(row.authorization.authorization_no)}`}>{row.authorization.authorization_no}</Link></div>}{kind==='deployments' && <div><Link href={`/production/changeovers?deployment_id=${row.id}`}>{row.changeover_count} changeovers</Link> · <Link href={`/production/batches?deployment_id=${row.id}`}>{row.batch_count} batches</Link></div>}{kind==='batches' && <div>{row.changeover ? row.changeover.changeover_no : row.changeover_linked ? 'Linked changeover missing' : 'No changeover linked'}</div>}<div>{row.recorded_at || 'Time not recorded'}</div></td><td>{row.customer ? <Link href={`/customers/${encodeURIComponent(row.customer.code)}`}>{row.customer.code}</Link> : 'Customer missing'}<div>{row.project ? <Link href={`/projects/${row.project.id}`}>{row.project.code}</Link> : 'Project missing'}</div>{row.site ? <Link href={`/manufacturing/sites/${encodeURIComponent(row.site.site_code)}`}>{row.site.site_code}</Link> : 'Site missing'} / {row.line?.line_code || 'Line missing'}</td><td>{kind==='deployments' ? software(row.expected) : kind==='changeovers' ? <>{software(row.from_release)}<p>→</p>{software(row.recorded)}</> : software(row.recorded)}</td><td>{software(row.actual)}<div>{row.software_observation}</div></td><td>{row.status}{!row.context_consistent && <p className="muted">Binding review: {row.binding_flags.join(', ')}</p>}</td></tr>)}</tbody></table>{!data.items.length && <p className="muted">No matching records.</p>}<p>{filters.offset && <Link href={`${paths[kind]}?${first}`}>First page</Link>}{data.next_offset !== null && <Link href={`${paths[kind]}?${next}`}> Next page →</Link>}</p></section> : <section className="panel"><h2>Catalog unavailable</h2><p className="muted">The API is unavailable or a filter is invalid.</p></section>}
  </>;
}
