import Link from 'next/link';
import { apiGet } from '../../../lib/api';

type Overview={version:string;status:string;software:{name:string;code:string}|null;customer:{name:string;code:string}|null;project:{name:string;code:string}|null;base_release:{version:string}|null;snapshot:{snapshot_no:string;status:string;content_hash:string}|null;coverage:{change_points_total:number;change_points_covered:number;change_coverage:number;issues_total:number;issues_covered:number;issue_verification_coverage:number;required_dvp_total:number;current_snapshot_passed:number;current_snapshot_executed:number;dvp_execution_coverage:number;snapshot_match:boolean;snapshot_no:string|null}};
const fallback:Overview={version:'2.3.4',status:'READY',software:{name:'BMS Standard',code:'SW-BMS-001'},customer:{name:'Customer A',code:'CUS-001'},project:{name:'Project X',code:'PRJ-X'},base_release:{version:'5.1.12'},snapshot:{snapshot_no:'SNAP-008',status:'FROZEN',content_hash:'5c8e7f41…91af'},coverage:{change_points_total:2,change_points_covered:2,change_coverage:100,issues_total:1,issues_covered:1,issue_verification_coverage:100,required_dvp_total:3,current_snapshot_passed:2,current_snapshot_executed:2,dvp_execution_coverage:67,snapshot_match:true,snapshot_no:'SNAP-008'}};
export default async function Page(){
 const apiData=await apiGet<Overview>('/api/v1/releases/application/2.3.4/overview');
 const d=apiData||fallback;
 return <><div className="cards"><Link className="card" href="/changes/SCR-142"><span className="muted">CHANGE CONTROL</span><div className="metric">{d.coverage.change_coverage}%</div><small>{d.coverage.change_points_covered} / {d.coverage.change_points_total} change points covered</small></Link><Link className="card" href="/releases/demo/verification"><span className="muted">VERIFICATION</span><div className="metric">{d.coverage.dvp_execution_coverage}%</div><small>{d.coverage.current_snapshot_executed} / {d.coverage.required_dvp_total} on current snapshot</small></Link><Link className="card" href="/releases/demo/components"><span className="muted">SNAPSHOT</span><div className="metric">{d.snapshot?.snapshot_no||'—'}</div><small>{d.snapshot?.status||'No snapshot'}</small></Link><Link className="card" href="/releases/demo/readiness"><span className="muted">STATUS</span><div className="metric">{d.status}</div><small>{d.coverage.snapshot_match?'Current snapshot tested':'Snapshot mismatch'}</small></Link></div><div className="grid2"><section className="panel"><h2>Release identity</h2><div className="kv"><span>Software</span><b>{d.software?.name||'—'}</b><span>Release</span><b>ASR {d.version}</b><span>Customer / Project</span><b>{d.customer?.name||'—'} / {d.project?.name||'—'}</b><span>Base SSR</span><b>{d.base_release?'SSR '+d.base_release.version:'—'}</b><span>Frozen snapshot</span><b>{d.snapshot?.snapshot_no||'—'}</b><span>Content hash</span><code>{d.snapshot?.content_hash||'—'}</code></div></section><section className="panel"><h2>Traceability coverage</h2><div className="timeline"><div><b>Change coverage {d.coverage.change_coverage}%</b><span>{d.coverage.change_points_covered} / {d.coverage.change_points_total} change points linked to DVP</span></div><div><b>Issue coverage {d.coverage.issue_verification_coverage}%</b><span>{d.coverage.issues_covered} / {d.coverage.issues_total} verification-required issues covered</span></div><div><b>Current snapshot execution {d.coverage.dvp_execution_coverage}%</b><span>{d.coverage.current_snapshot_executed} / {d.coverage.required_dvp_total} required DVP executed</span></div></div></section></div>{!apiData&&<p className="datasource">Demo fallback active · release overview API will load automatically when backend is configured.</p>}</>
}