
import { Localized, LocalizedAttributes } from "../../../components/localized";
import Link from 'next/link';
import { apiGet } from '../../../lib/api';
import type { Context, Execution, ReleaseOption } from '../../../lib/dvp-types';

type Catalog = { context: Context; total: number; summary: { executed: number; not_executed: number; retested: number; recorded_latest_results: Record<string, number> }; items: { id: string; item_no: string; title: string; scope: string; status: string; plan_no: string; request_no: string; execution_count: number; latest_execution: Execution | null }[]; next_offset: number | null; release_options: ReleaseOption[]; release_options_truncated: boolean };

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const filters = await searchParams;
  const query = new URLSearchParams();
  for (const key of ['scr', 'plan', 'scope', 'status', 'result', 'q', 'release_id', 'snapshot_no', 'offset']) if (filters[key]) query.set(key, filters[key]!);
  const data = await apiGet<Catalog>(`/api/v1/testing/dvp/catalog?${query}`);
  const next = new URLSearchParams(query); if (data?.next_offset !== null && data?.next_offset !== undefined) next.set('offset', String(data.next_offset));
  const first = new URLSearchParams(query); first.delete('offset');
  return <>
    <div className="top"><div><div className="eyebrow"><Localized>{"VERIFICATION"}</Localized></div><h1><Localized>{"DVP & Test Execution"}</Localized></h1><p className="muted"><Localized>{"Browse test assignments and recorded results by SCR, plan, scope, status and frozen snapshot."}</Localized></p></div></div>
    <section className="panel"><form method="get" className="filters"><label><Localized>{"SCR "}</Localized><LocalizedAttributes><input name="scr" defaultValue={filters.scr || ''} placeholder="SCR-142" maxLength={50} /></LocalizedAttributes></label><label><Localized>{"Plan "}</Localized><LocalizedAttributes><input name="plan" defaultValue={filters.plan || ''} placeholder="DVP-PLAN-142" maxLength={50} /></LocalizedAttributes></label><label><Localized>{"Scope "}</Localized><LocalizedAttributes><input name="scope" defaultValue={filters.scope || ''} placeholder="SOFTWARE_TEST" maxLength={30} /></LocalizedAttributes></label><label><Localized>{"Declared status "}</Localized><LocalizedAttributes><input name="status" defaultValue={filters.status || ''} placeholder="COMPLETED" maxLength={30} /></LocalizedAttributes></label><label><Localized>{"Latest result "}</Localized><LocalizedAttributes><input name="result" defaultValue={filters.result || ''} placeholder="PASS / FAIL / NOT_EXECUTED" maxLength={30} /></LocalizedAttributes></label><label><Localized>{"Search "}</Localized><LocalizedAttributes><input name="q" defaultValue={filters.q || ''} placeholder="Item, title, plan or SCR" maxLength={200} /></LocalizedAttributes></label><label><Localized>{"Release "}</Localized><select name="release_id" defaultValue={filters.release_id || ''}><option value=""><Localized>{"All recorded contexts"}</Localized></option><Localized>{filters.release_id && !data?.release_options.some(r => r.id === filters.release_id) && <option value={filters.release_id}><Localized>{data?.context.release?.version || 'Selected release'}</Localized></option>}</Localized><Localized>{data?.release_options.map(r => <option key={r.id} value={r.id}><Localized>{r.type === 'APPLICATION' ? 'ASR' : 'SSR'}</Localized> <Localized>{r.version}</Localized></option>)}</Localized></select></label><label><Localized>{"Historical snapshot "}</Localized><LocalizedAttributes><input name="snapshot_no" defaultValue={filters.snapshot_no || ''} placeholder="Latest frozen snapshot" maxLength={80} /></LocalizedAttributes></label><button type="submit"><Localized>{"Filter"}</Localized></button><Link href="/testing/dvp"><Localized>{"Reset"}</Localized></Link></form>
    <Localized>{data && <p className="muted"><Localized>{data.context.snapshot ? `Exact execution context: ${data.context.snapshot.snapshot_no}` : data.context.release ? 'Selected release has no frozen snapshot; no executions are counted.' : 'Latest recorded execution across all contexts; this does not establish verification of a current release.'}</Localized><Localized>{" Retested means at least two executions within the selected context."}</Localized></p>}</Localized><Localized>{data?.release_options_truncated && <p className="muted"><Localized>{"The release selector shows the first 100 releases."}</Localized></p>}</Localized></section>
    <Localized>{data ? <><div className="cards"><div className="card"><span className="muted"><Localized>{"FILTERED TEST ITEMS"}</Localized></span><div className="metric"><Localized>{data.total}</Localized></div></div><div className="card"><span className="muted"><Localized>{"LATEST RECORDED PASS"}</Localized></span><div className="metric"><Localized>{data.summary.recorded_latest_results.PASS || 0}</Localized><Localized>{" / "}</Localized><Localized>{data.summary.executed}</Localized></div></div><div className="card"><span className="muted"><Localized>{"RETESTED / UNEXECUTED"}</Localized></span><div className="metric"><Localized>{data.summary.retested}</Localized><Localized>{" / "}</Localized><Localized>{data.summary.not_executed}</Localized></div></div></div>
    <section className="panel tablewrap"><p className="muted"><Localized>{"Summary covers all filtered records. Result counts are recorded outcomes; each execution shows its context consistency."}</Localized></p><table><thead><tr><th><Localized>{"DVP / Plan"}</Localized></th><th><Localized>{"Test Item / SCR"}</Localized></th><th><Localized>{"Scope / Status"}</Localized></th><th><Localized>{"Latest Result"}</Localized></th><th><Localized>{"Execution Context"}</Localized></th><th><Localized>{"Context Executions"}</Localized></th></tr></thead><tbody><Localized>{data.items.map(row => { const e = row.latest_execution; const itemQuery = new URLSearchParams(); if (filters.release_id) itemQuery.set('release_id', filters.release_id); if (filters.snapshot_no) itemQuery.set('snapshot_no', filters.snapshot_no); return <tr key={row.id}><td><Link href={`/testing/dvp/${row.id}?${itemQuery}`}><b><Localized>{row.item_no}</Localized></b></Link><div><Localized>{row.plan_no}</Localized></div></td><td><Localized>{row.title}</Localized><div><Link href={`/changes/${encodeURIComponent(row.request_no)}`}><Localized>{row.request_no}</Localized></Link></div></td><td><Localized>{row.scope}</Localized><div><Localized>{row.status}</Localized></div></td><td><Localized>{e ? <><span className={'status ' + (e.result === 'PASS' && e.context_consistent ? 'pass' : 'warning')}><Localized>{e.result}</Localized></span><div><Localized>{"#"}</Localized><Localized>{e.execution_no}</Localized></div><Localized>{!e.context_consistent && <div className="muted"><Localized>{"Context mismatch; review record"}</Localized></div>}</Localized></> : 'Not executed'}</Localized></td><td><Localized>{e ? <><Link href={`/releases/${e.release_type === 'APPLICATION' ? 'application' : 'standard'}/${e.release_id}`}><Localized>{e.release_type === 'APPLICATION' ? 'ASR' : 'SSR'}</Localized> <Localized>{e.release_version}</Localized></Link><div><Localized>{e.snapshot_no ? <Link href={`/snapshots/${encodeURIComponent(e.snapshot_no)}`}><Localized>{e.snapshot_no}</Localized></Link> : e.snapshot_id}</Localized></div></> : '—'}</Localized></td><td><Localized>{row.execution_count}</Localized></td></tr>; })}</Localized></tbody></table><Localized>{!data.items.length && <p className="muted"><Localized>{"No matching DVP items."}</Localized></p>}</Localized><p><Localized>{filters.offset && <Link href={`/testing/dvp?${first}`}><Localized>{"First page"}</Localized></Link>}</Localized><Localized>{data.next_offset !== null && <Link href={`/testing/dvp?${next}`}><Localized>{" Next page →"}</Localized></Link>}</Localized></p></section></> : <section className="panel"><h2><Localized>{"DVP catalog unavailable"}</Localized></h2><p className="muted"><Localized>{"The API is unavailable or filters are invalid. Historical snapshot selection requires its release."}</Localized></p><Link href="/testing/dvp"><Localized>{"Reset filters →"}</Localized></Link></section>}</Localized>
  </>;
}
