
import { Localized, LocalizedAttributes } from "../components/localized";
import './globals.css';
import { cookies } from 'next/headers';
import { resolveLocale } from '../lib/i18n';
import { LanguageProvider } from '../components/localized';
import Link from 'next/link';
export async function generateMetadata() {
  const locale = resolveLocale((await cookies()).get('slc_language')?.value);
  return { title: locale === 'zh' ? 'SoftwareLifeCycle · 软件生命周期治理' : 'SoftwareLifeCycle · Software lifecycle governance' };
}
export default async function RootLayout({children}:{children:React.ReactNode}){
const locale = resolveLocale((await cookies()).get('slc_language')?.value);
return <html lang={locale === 'zh' ? 'zh-CN' : 'en'}><body><LanguageProvider initialLocale={locale}><div className="shell"><aside className="side"><Link className="brand" href="/"><Localized>{"SoftwareLifeCycle"}</Localized><span><Localized>{"Automotive Governance"}</Localized></span></Link><nav className="nav"><small><Localized>{"WORKSPACE"}</Localized></small><Link href="/"><Localized>{"Dashboard"}</Localized></Link><Link href="/changes"><Localized>{"Changes"}</Localized></Link><Link href="/testing/dvp"><Localized>{"Testing / DVP"}</Localized></Link><Link href="/testing/releases"><Localized>{"Test Releases"}</Localized></Link><Link href="/releases/standard"><Localized>{"Standard Releases"}</Localized></Link><Link href="/releases/application"><Localized>{"Application Releases"}</Localized></Link><Link href="/issues"><Localized>{"Issues"}</Localized></Link><Link href="/releases/matrix"><Localized>{"Release Matrix"}</Localized></Link><small><Localized>{"ORGANIZATION"}</Localized></small><Link href="/suppliers"><Localized>{"Suppliers"}</Localized></Link><Link href="/customers"><Localized>{"Customers"}</Localized></Link><Link href="/projects"><Localized>{"Projects"}</Localized></Link><small><Localized>{"DELIVERY & PRODUCTION"}</Localized></small><Link href="/distribution/deliveries"><Localized>{"Distribution"}</Localized></Link><Link href="/distribution/authorizations"><Localized>{"Authorizations"}</Localized></Link><Link href="/manufacturing/sites"><Localized>{"Manufacturing Sites"}</Localized></Link><Link href="/deployments"><Localized>{"Deployments"}</Localized></Link><Link href="/production/changeovers"><Localized>{"Software Changeovers"}</Localized></Link><Link href="/production/batches"><Localized>{"Production Batches"}</Localized></Link><small><Localized>{"GOVERNANCE"}</Localized></small><Link href="/approvals"><Localized>{"Approvals"}</Localized></Link><Link href="/release-decisions"><Localized>{"Release Decisions"}</Localized></Link><Link href="/resources"><Localized>{"Resources"}</Localized></Link><Link href="/activity"><Localized>{"Activity"}</Localized></Link></nav><div className="sidefoot"><Localized>{"V1 · Local First"}</Localized></div></aside><main className="main"><header className="appbar"><Link className="search" href="/search"><Localized>{"⌕ Search software, release, issue…"}</Localized></Link><div className="appactions"><Link href="/create"><Localized>{"＋ Create"}</Localized></Link><Link href="/activity"><Localized>{"◉"}</Localized></Link></div></header><div className="content"><Localized>{children}</Localized></div></main></div></LanguageProvider></body></html>}
