import Link from 'next/link';
import { apiGet } from '../../../../lib/api';

type DecisionResponse={decision:null|{decision_no:string;decision:string;readiness_status:string;decided_by:string;decision_notes:string|null;snapshot_no:string|null;approval_no:string|null}};
const fallback:DecisionResponse={decision:{decision_no:'RD-0081',decision:'RELEASE',readiness_status:'READY_WITH_EXCEPTION',decided_by:'Release Manager',decision_notes:'Released with PEX-0018 controlled initial-production restriction.',snapshot_no:'SNAP-008',approval_no:'APR-0121'}};

export default async function Page(){
 const apiData=await apiGet<DecisionResponse>('/api/v1/releases/application/2.3.4/decision');
 const d=apiData||fallback;
 return <><div className="passportHero"><div><span className="eyebrow">SOFTWARE PASSPORT</span><h2>ASR 2.3.4</h2><p>Customer A · Project X · BMS · SNAP-008</p></div><span className={'status '+(d.decision?.decision==='RELEASE'?'pass':'warning')}>{d.decision?.decision==='RELEASE'?'RELEASED':'RELEASE CANDIDATE'}</span></div><div className="passportgrid"><section className="panel"><h2>Identity & provenance</h2><div className="kv"><span>Supplier</span><b>Supplier A</b><span>Software</span><b>BMS Standard</b><span>Base SSR</span><b>5.1.12</b><span>Snapshot</span><b>SNAP-008</b></div></section><section className="panel"><h2>Why changed</h2><p><b>SCR-142</b> addresses Issue #310 low-temperature charging timeout and calibration behavior.</p></section><section className="panel"><h2>Verification</h2><div className="metric">Current</div><p>DVP evidence is bound to the current snapshot.</p></section><section className="panel"><h2>Governance</h2><div className="kv"><span>Approval</span><b>{d.decision?.approval_no||'APR-0121 PENDING'}</b><span>Decision</span><b>{d.decision?.decision||'NOT DECIDED'}</b><span>Readiness</span><b>{d.decision?.readiness_status||'READY'}</b></div></section><section className="panel"><h2>Release Decision</h2>{d.decision?<div className="kv"><span>Decision No.</span><b>{d.decision.decision_no}</b><span>Decided by</span><b>{d.decision.decided_by}</b><span>Snapshot</span><b>{d.decision.snapshot_no||'—'}</b><span>Notes</span><b>{d.decision.decision_notes||'—'}</b></div>:<div className="notice">No final Release Decision has been recorded. Approval completion does not automatically release or distribute software.</div>}</section><section className="panel"><h2>Distribution & authorization</h2><p>Released content is packaged in DP-0226, distributed as DIST-0326, and production-authorized by PA-0081.</p><Link href="/distribution/deliveries/new"><b>Open delivery chain →</b></Link></section></div>{!apiData&&<p className="datasource">Demo fallback active.</p>}</>
}
