
import { Localized, LocalizedAttributes } from "../../components/localized";
import Link from 'next/link';
import { apiGet } from '../../lib/api';
import { entityTypes, type Resource } from '../../lib/resources';
type Catalog = { total: number; kind_counts: Record<string, number>; next_offset: number | null; items: Resource[] };
export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const filters = await searchParams; const query = new URLSearchParams();
  for (const key of ['entity_type','entity_id','location_kind','q','offset']) if (filters[key]) query.set(key,filters[key]!);
  const data = await apiGet<Catalog>(`/api/v1/resources?${query}`);
  const first = new URLSearchParams(query); first.delete('offset');
  const next = new URLSearchParams(query); if (data?.next_offset !== null && data?.next_offset !== undefined) next.set('offset',String(data.next_offset));
  return <><div className="top"><div><div className="eyebrow"><Localized>{"MATERIALS & EVIDENCE REFERENCES"}</Localized></div><h1><Localized>{"Resources"}</Localized></h1><Link href="/commands?operation=resource"><Localized>{"Prepare resource reference →"}</Localized></Link><p className="muted"><Localized>{"Recorded locations associated with business objects. References do not prove file contents, availability or permission to distribute."}</Localized></p></div></div>
    <section className="panel"><form method="get" className="filters"><label><Localized>{"Object type "}</Localized><select name="entity_type" defaultValue={filters.entity_type || ''}><option value=""><Localized>{"All objects"}</Localized></option><Localized>{entityTypes.map(t => <option value={t} key={t}><Localized>{t}</Localized></option>)}</Localized></select></label><label><Localized>{"Location "}</Localized><select name="location_kind" defaultValue={filters.location_kind || ''}><option value=""><Localized>{"All locations"}</Localized></option><Localized>{['WEB_URL','LOCAL_PATH','NETWORK_PATH'].map(t => <option value={t} key={t}><Localized>{t}</Localized></option>)}</Localized></select></label><label><Localized>{"Search "}</Localized><LocalizedAttributes><input name="q" defaultValue={filters.q || ''} maxLength={200} placeholder="Title, description or object reference" /></LocalizedAttributes></label><Localized>{filters.entity_id && <input type="hidden" name="entity_id" value={filters.entity_id} />}</Localized><button type="submit"><Localized>{"Filter"}</Localized></button><Link href="/resources"><Localized>{"Reset"}</Localized></Link></form><Localized>{filters.entity_id && <p className="muted"><Localized>{"Object ID: "}</Localized><Localized>{filters.entity_id}</Localized><Localized>{" · "}</Localized><Link href={`/commands?${new URLSearchParams({operation:"resource",target:filters.entity_id,entity_type:filters.entity_type||""})}`}><Localized>{"Prepare reference for this filtered object →"}</Localized></Link></p>}</Localized><p className="muted"><Localized>{"Public test environment is read-only. Local API registration is append-only and audited. Locations are never fetched by the server."}</Localized></p></section>
    <Localized>{data ? <section className="panel tablewrap"><h2><Localized>{data.total}</Localized><Localized>{" matching resources"}</Localized></h2><p className="muted"><Localized>{Object.entries(data.kind_counts).map(([k,n]) => `${k}: ${n}`).join(' · ') || 'No location records'}</Localized><Localized>{" · Counts cover all filtered records."}</Localized></p><table><thead><tr><th><Localized>{"Resource"}</Localized></th><th><Localized>{"Business object"}</Localized></th><th><Localized>{"Location kind"}</Localized></th><th><Localized>{"Recorded by / time"}</Localized></th></tr></thead><tbody><Localized>{data.items.map(row => <tr key={row.id}><td><Link href={`/resources/${row.id}`}><Localized>{row.title}</Localized></Link><div><Localized>{row.description}</Localized></div></td><td><Localized>{row.entity_type}</Localized><div><Link href={row.entity_href}><Localized>{row.entity_ref}</Localized></Link></div></td><td><Localized>{row.location_kind}</Localized></td><td><Localized>{row.actor_name}</Localized><div><Localized>{row.created_at}</Localized></div></td></tr>)}</Localized></tbody></table><Localized>{!data.items.length && <p className="muted"><Localized>{"No resources recorded for these filters. Existing artifact storage references remain in their original records."}</Localized></p>}</Localized><p><Localized>{filters.offset && <Link href={`/resources?${first}`}><Localized>{"First page"}</Localized></Link>}</Localized><Localized>{data.next_offset !== null && <Link href={`/resources?${next}`}><Localized>{" Next page →"}</Localized></Link>}</Localized></p></section> : <section className="panel"><h2><Localized>{"Resource catalog unavailable"}</Localized></h2><p className="muted"><Localized>{"The API is unavailable or a filter is invalid."}</Localized></p></section>}</Localized>
  </>;
}
