import Link from 'next/link';
import { apiGet } from '../../lib/api';
import { entityTypes, type Resource } from '../../lib/resources';
type Catalog = { total: number; kind_counts: Record<string, number>; next_offset: number | null; items: Resource[] };
export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const filters = await searchParams; const query = new URLSearchParams();
  for (const key of ['entity_type','entity_id','location_kind','q','offset']) if (filters[key]) query.set(key,filters[key]!);
  const data = await apiGet<Catalog>(`/api/v1/resources?${query}`);
  const first = new URLSearchParams(query); first.delete('offset');
  const next = new URLSearchParams(query); if (data?.next_offset !== null && data?.next_offset !== undefined) next.set('offset',String(data.next_offset));
  return <><div className="top"><div><div className="eyebrow">MATERIALS & EVIDENCE REFERENCES</div><h1>Resources</h1><Link href="/commands?operation=resource">Prepare resource reference →</Link><p className="muted">Recorded locations associated with business objects. References do not prove file contents, availability or permission to distribute.</p></div></div>
    <section className="panel"><form method="get" className="filters"><label>Object type <select name="entity_type" defaultValue={filters.entity_type || ''}><option value="">All objects</option>{entityTypes.map(t => <option key={t}>{t}</option>)}</select></label><label>Location <select name="location_kind" defaultValue={filters.location_kind || ''}><option value="">All locations</option>{['WEB_URL','LOCAL_PATH','NETWORK_PATH'].map(t => <option key={t}>{t}</option>)}</select></label><label>Search <input name="q" defaultValue={filters.q || ''} maxLength={200} placeholder="Title, description or object reference" /></label>{filters.entity_id && <input type="hidden" name="entity_id" value={filters.entity_id} />}<button type="submit">Filter</button><Link href="/resources">Reset</Link></form>{filters.entity_id && <p className="muted">Object ID: {filters.entity_id} · <Link href={`/commands?${new URLSearchParams({operation:"resource",target:filters.entity_id,entity_type:filters.entity_type||""})}`}>Prepare reference for this filtered object →</Link></p>}<p className="muted">Public test environment is read-only. Local API registration is append-only and audited. Locations are never fetched by the server.</p></section>
    {data ? <section className="panel tablewrap"><h2>{data.total} matching resources</h2><p className="muted">{Object.entries(data.kind_counts).map(([k,n]) => `${k}: ${n}`).join(' · ') || 'No location records'} · Counts cover all filtered records.</p><table><thead><tr><th>Resource</th><th>Business object</th><th>Location kind</th><th>Recorded by / time</th></tr></thead><tbody>{data.items.map(row => <tr key={row.id}><td><Link href={`/resources/${row.id}`}>{row.title}</Link><div>{row.description}</div></td><td>{row.entity_type}<div><Link href={row.entity_href}>{row.entity_ref}</Link></div></td><td>{row.location_kind}</td><td>{row.actor_name}<div>{row.created_at}</div></td></tr>)}</tbody></table>{!data.items.length && <p className="muted">No resources recorded for these filters. Existing artifact storage references remain in their original records.</p>}<p>{filters.offset && <Link href={`/resources?${first}`}>First page</Link>}{data.next_offset !== null && <Link href={`/resources?${next}`}> Next page →</Link>}</p></section> : <section className="panel"><h2>Resource catalog unavailable</h2><p className="muted">The API is unavailable or a filter is invalid.</p></section>}
  </>;
}
