"""core software/release/artifact/snapshot tables"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0001_core_and_snapshot'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('suppliers',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('code',sa.String(50),nullable=False,unique=True),sa.Column('name',sa.String(200),nullable=False),sa.Column('country',sa.String(100)),sa.Column('website',sa.Text()),sa.Column('description',sa.Text()),sa.Column('status',sa.String(30),nullable=False))
    op.create_table('customers',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('code',sa.String(50),nullable=False,unique=True),sa.Column('name',sa.String(200),nullable=False),sa.Column('status',sa.String(30),nullable=False))
    op.create_table('projects',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('customer_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('customers.id'),nullable=False),sa.Column('project_code',sa.String(50),nullable=False),sa.Column('name',sa.String(200),nullable=False),sa.Column('vehicle_platform',sa.String(200)),sa.Column('status',sa.String(30),nullable=False),sa.UniqueConstraint('customer_id','project_code'))
    op.create_table('software_products',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('supplier_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('suppliers.id'),nullable=False),sa.Column('code',sa.String(50),nullable=False,unique=True),sa.Column('name',sa.String(200),nullable=False),sa.Column('software_type',sa.String(50)),sa.Column('status',sa.String(30),nullable=False))
    op.create_table('releases',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('software_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('software_products.id'),nullable=False),sa.Column('release_type',sa.String(20),nullable=False),sa.Column('version',sa.String(100),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('release_notes',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True)),sa.CheckConstraint("release_type IN ('STANDARD','APPLICATION')",name='ck_release_type'),sa.UniqueConstraint('software_id','release_type','version'))
    op.create_table('standard_release_details',sa.Column('release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('releases.id'),primary_key=True),sa.Column('previous_release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('releases.id')),sa.Column('git_repository',sa.Text()),sa.Column('git_branch',sa.Text()),sa.Column('git_commit',sa.String(100)))
    op.create_table('application_release_details',sa.Column('release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('releases.id'),primary_key=True),sa.Column('customer_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('customers.id'),nullable=False),sa.Column('project_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('projects.id'),nullable=False),sa.Column('standard_base_release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('releases.id'),nullable=False),sa.Column('previous_application_release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('releases.id')))
    op.create_table('component_definitions',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('code',sa.String(80),nullable=False,unique=True),sa.Column('name',sa.String(120),nullable=False),sa.Column('is_active',sa.Boolean(),nullable=False))
    op.create_table('release_components',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('releases.id'),nullable=False),sa.Column('component_definition_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('component_definitions.id'),nullable=False),sa.Column('version',sa.String(100)),sa.Column('base_component_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('release_components.id')),sa.Column('delta_type',sa.String(20),nullable=False),sa.CheckConstraint("delta_type IN ('UNCHANGED','MODIFIED','ADDED','REMOVED')",name='ck_delta_type'))
    op.create_table('artifacts',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('release_component_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('release_components.id'),nullable=False),sa.Column('artifact_type',sa.String(80),nullable=False),sa.Column('filename',sa.String(255),nullable=False),sa.Column('storage_reference',sa.Text(),nullable=False),sa.Column('file_size',sa.Integer()),sa.Column('sha256',sa.String(64)),sa.Column('controlled',sa.Boolean(),nullable=False),sa.Column('classification',sa.String(40),nullable=False),sa.Column('distribution_level',sa.String(40)),sa.Column('ai_access_policy',sa.String(40),nullable=False),sa.CheckConstraint("controlled = false OR (sha256 IS NOT NULL AND distribution_level IS NOT NULL)",name='ck_controlled_artifact_integrity'))
    op.create_index('ix_artifacts_sha256','artifacts',['sha256'])
    op.create_table('release_snapshots',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('snapshot_no',sa.String(80),nullable=False,unique=True),sa.Column('release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('releases.id'),nullable=False),sa.Column('snapshot_number',sa.Integer(),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.Column('release_metadata_json',postgresql.JSONB(),nullable=False),sa.Column('content_hash',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('release_id','snapshot_number'))
    op.create_table('snapshot_artifacts',sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True),sa.Column('snapshot_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('release_snapshots.id'),nullable=False),sa.Column('source_artifact_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('artifacts.id'),nullable=False),sa.Column('component_code',sa.String(80),nullable=False),sa.Column('component_version',sa.String(100)),sa.Column('filename',sa.String(255),nullable=False),sa.Column('artifact_type',sa.String(80),nullable=False),sa.Column('sha256',sa.String(64),nullable=False),sa.Column('classification',sa.String(40),nullable=False),sa.Column('distribution_level',sa.String(40),nullable=False),sa.Column('ai_access_policy',sa.String(40),nullable=False),sa.Column('storage_reference',sa.Text(),nullable=False))
    op.create_index('ix_snapshot_artifacts_snapshot_id','snapshot_artifacts',['snapshot_id']); op.create_index('ix_snapshot_artifacts_sha256','snapshot_artifacts',['sha256'])

def downgrade():
    for table in ['snapshot_artifacts','release_snapshots','artifacts','release_components','component_definitions','application_release_details','standard_release_details','releases','software_products','projects','customers','suppliers']: op.drop_table(table)
