"""change issue and testing traceability"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0002_change_testing'; down_revision='0001_core_and_snapshot'; branch_labels=None; depends_on=None

def idcol(): return sa.Column('id',postgresql.UUID(as_uuid=True),primary_key=True)

def upgrade():
    op.create_table('software_change_requests',idcol(),sa.Column('request_no',sa.String(50),nullable=False,unique=True),sa.Column('title',sa.String(240),nullable=False),sa.Column('source',sa.String(30),nullable=False),sa.Column('scope',sa.String(20),nullable=False),sa.Column('change_type',sa.String(40),nullable=False),sa.Column('software_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('software_products.id'),nullable=False),sa.Column('customer_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('customers.id')),sa.Column('project_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('projects.id')),sa.Column('status',sa.String(40),nullable=False),sa.Column('background',sa.Text()),sa.Column('requirement',sa.Text()),sa.Column('created_at',sa.DateTime(timezone=True)))
    op.create_table('acceptance_criteria',idcol(),sa.Column('change_request_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('software_change_requests.id'),nullable=False),sa.Column('criterion_no',sa.String(50),nullable=False),sa.Column('description',sa.Text(),nullable=False))
    op.create_table('change_points',idcol(),sa.Column('change_request_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('software_change_requests.id'),nullable=False),sa.Column('change_no',sa.String(50),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('description',sa.Text()),sa.Column('status',sa.String(30),nullable=False))
    op.create_table('issues',idcol(),sa.Column('issue_no',sa.String(50),nullable=False,unique=True),sa.Column('title',sa.String(240),nullable=False),sa.Column('scope',sa.String(30),nullable=False),sa.Column('severity',sa.String(20),nullable=False),sa.Column('status',sa.String(40),nullable=False),sa.Column('description',sa.Text()))
    op.create_table('issue_change_request_relations',idcol(),sa.Column('issue_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('issues.id'),nullable=False),sa.Column('change_request_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('software_change_requests.id'),nullable=False),sa.Column('relation_type',sa.String(40),nullable=False),sa.UniqueConstraint('issue_id','change_request_id','relation_type'))
    op.create_table('dvp_plans',idcol(),sa.Column('change_request_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('software_change_requests.id'),nullable=False),sa.Column('plan_no',sa.String(50),nullable=False,unique=True),sa.Column('title',sa.String(240),nullable=False),sa.Column('status',sa.String(30),nullable=False))
    op.create_table('dvp_items',idcol(),sa.Column('plan_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('dvp_plans.id'),nullable=False),sa.Column('item_no',sa.String(50),nullable=False),sa.Column('title',sa.String(240),nullable=False),sa.Column('scope',sa.String(30),nullable=False),sa.Column('status',sa.String(30),nullable=False),sa.UniqueConstraint('plan_id','item_no'))
    op.create_table('change_point_dvp_items',sa.Column('change_point_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('change_points.id'),primary_key=True),sa.Column('dvp_item_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('dvp_items.id'),primary_key=True),sa.Column('relation_type',sa.String(30),nullable=False))
    op.create_table('issue_dvp_items',sa.Column('issue_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('issues.id'),primary_key=True),sa.Column('dvp_item_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('dvp_items.id'),primary_key=True),sa.Column('relation_type',sa.String(30),nullable=False))
    op.create_table('test_releases',idcol(),sa.Column('test_release_no',sa.String(50),nullable=False,unique=True),sa.Column('release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('releases.id'),nullable=False),sa.Column('snapshot_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('release_snapshots.id'),nullable=False),sa.Column('purpose_scope',sa.String(30),nullable=False),sa.Column('status',sa.String(30),nullable=False))
    op.create_table('dvp_executions',idcol(),sa.Column('dvp_item_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('dvp_items.id'),nullable=False),sa.Column('execution_no',sa.Integer(),nullable=False),sa.Column('release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('releases.id'),nullable=False),sa.Column('snapshot_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('release_snapshots.id'),nullable=False),sa.Column('test_release_id',postgresql.UUID(as_uuid=True),sa.ForeignKey('test_releases.id')),sa.Column('result',sa.String(30),nullable=False),sa.Column('actual_result',sa.Text()),sa.Column('executed_at',sa.DateTime(timezone=True)),sa.UniqueConstraint('dvp_item_id','execution_no'))

def downgrade():
    for t in ['dvp_executions','test_releases','issue_dvp_items','change_point_dvp_items','dvp_items','dvp_plans','issue_change_request_relations','issues','change_points','acceptance_criteria','software_change_requests']: op.drop_table(t)
