
import { Localized, LocalizedAttributes } from "../../../components/localized";
import Link from 'next/link';
import { apiGet } from '../../../lib/api';
import type { GovernanceRow } from '../../../lib/governance';
export default async function Page({params}:{params:Promise<{decisionNo:string}>}) {
  const {decisionNo}=await params;const row=await apiGet<GovernanceRow>(`/api/v1/governance/decisions/${encodeURIComponent(decisionNo)}`);
  if(!row)return <section className="panel"><h1><Localized>{"Release decision unavailable"}</Localized></h1><p className="muted"><Localized>{"The exact decision was not found or the API is unavailable."}</Localized></p><Link href="/release-decisions"><Localized>{"All decisions →"}</Localized></Link></section>;
  return <><div className="top"><div><div className="eyebrow"><Localized>{"EXACT RELEASE DECISION"}</Localized></div><h1><Localized>{row.decision_no}</Localized></h1><p><Localized>{row.decision}</Localized><Localized>{" · Recorded readiness: "}</Localized><Localized>{row.readiness_status}</Localized></p></div></div><section className="panel"><h2><Localized>{"Recorded software and approval"}</Localized></h2><Localized>{row.release?<p><Link href={`/releases/${row.release.type==='APPLICATION'?'application':'standard'}/${row.release.id}`}><Localized>{row.release.type}</Localized> <Localized>{row.release.version}</Localized></Link></p>:<p><Localized>{"Release missing"}</Localized></p>}</Localized><Localized>{row.snapshot?<><p><Link href={`/snapshots/${encodeURIComponent(row.snapshot.snapshot_no)}`}><Localized>{row.snapshot.snapshot_no}</Localized></Link></p><code style={{overflowWrap:'anywhere'}}>{row.snapshot.content_hash}</code></>:<p><Localized>{"Snapshot missing"}</Localized></p>}</Localized><Localized>{row.approval?<p><Link href={`/approvals/${encodeURIComponent(row.approval.approval_no)}`}><Localized>{row.approval.approval_no}</Localized></Link><Localized>{" · Current approval status: "}</Localized><Localized>{row.approval.status}</Localized></p>:<p><Localized>{"Approval missing"}</Localized></p>}</Localized><Localized>{!row.context_consistent&&<p className="muted"><Localized>{"Recorded release/snapshot/approval binding mismatch; review required."}</Localized></p>}</Localized><p className="muted"><Localized>{"This decision retains its original software binding. Current approval status and newer decisions do not replace this record."}</Localized></p></section><section className="panel"><h2><Localized>{"Decision record"}</Localized></h2><p><Localized>{"Declared actor: "}</Localized><Localized>{row.decided_by}</Localized></p><p><Localized>{row.decided_at}</Localized></p><p><Localized>{row.decision_notes||'No notes recorded.'}</Localized></p><p className="muted"><Localized>{"Actor identity and physical software are not established by this record. Existing delivery and production rules continue to apply."}</Localized></p></section><p><Link href={`/activity?${new URLSearchParams({entity_type: 'RELEASE_DECISION', entity_id: row.id})}`}><Localized>{"Audit history for this decision →"}</Localized></Link></p><Link href="/release-decisions"><Localized>{"All decisions →"}</Localized></Link></>;
}
