const {test,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const output=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'slc-evidence-'));
require('node:child_process').execFileSync(process.execPath,[require.resolve('typescript/bin/tsc'),'lib/acceptance-correction-transport.ts','lib/acceptance-correction-audit.ts','--target','ES2021','--module','commonjs','--strict','--skipLibCheck','--outDir',output]);
const {parseAcceptanceCorrectionCommand:parse,confirmAcceptanceCorrection:review,acceptanceCorrectionPath:fixedPath,projectAcceptanceCorrectionReceipt:project,AcceptanceCorrectionSubmission:Submission}=require(path.join(output,'acceptance-correction-transport.js'));
const {projectAcceptanceCorrectionAudit:audit}=require(path.join(output,'acceptance-correction-audit.js'));
const f=require('./fixtures/acceptance-correction.cjs'),copy=v=>JSON.parse(JSON.stringify(v));
after(()=>fs.rmSync(output,{recursive:true,force:true}));
test('exact predecessor context rejects self, cross-criterion, ended action and action/target mismatch',()=>{
 const c=f.command();for(const v of [
 {...c,body:{...c.body,action:'ASSIGN'}},{...c,body:{...c.body,supersedes_id:c.body.request_id}},
 {...c,predecessor:{...c.predecessor,action:'WITHDRAW'}},{...c,predecessor:{...c.predecessor,criterion_id:f.key}},
 {...c,predecessor:{...c.predecessor,id:f.key}},{...c,body:{...c.body,dvp_item_id:f.dvp}},
 {...f.command('WITHDRAW'),body:{...f.command('WITHDRAW').body,dvp_item_id:f.replacement}},
 {...c,predecessor:{...c.predecessor,token:'private'}}])assert.equal(parse(v),null);
});
test('correction of prior SUPERSEDE binds historical previous action and strips successor/current evidence',async()=>{
 for(const action of ['SUPERSEDE','WITHDRAW']){const c=parse(f.command(action,'SUPERSEDE')),e=f.audit(c);
 e.superseded_by_id=f.key;e.effective=false;e.current_status='PASSED';
 const r=await audit(e,c,f.principal);assert.deepEqual(r,f.receipt(c));assert.equal(r.result.superseded_by_id,undefined);
 e.payload.previous_action='ASSIGN';assert.equal(await audit(e,c,f.principal),null);
 e.action='ASSIGN';assert.equal(await audit(e,c,f.principal),null);}
});
for(const operation of ['SUPERSEDE','WITHDRAW']) {
 test(operation+' canonical exact fields, existing fixed path and request UUID remain frozen',()=>{const c=parse(f.command(operation));assert.deepEqual(c,f.command(operation));assert.ok(Object.isFrozen(c.body));assert.equal(fixedPath(c),'/api/v1/changes/'+encodeURIComponent(c.target)+'/acceptance-dvp-links');assert.equal(review(c,true).command.body.request_id,c.body.request_id);});
 test(operation+' parser rejects invalid target/UUID and credential injection',()=>{const c=f.command(operation);for(const v of [null,{...c,url:'https://evil'},{...c,operation:'resource'},{...c,target:'../evil'},{...c,body:{...c.body,request_id:'invalid'}},{...c,body:{...c.body,token:'private'}},{...c,body:{...c.body,reason:' '}},{...c,body:{...c.body,reason:'中'.repeat(3000)}},{...c,body:{...c.body,actor_name:'\ud800'}}])assert.equal(parse(v),null);});
 test(operation+' normalized declarations, target and UUID case match existing preparation',()=>{const c=f.command(operation);c.target=' '+c.target+' ';c.body.request_id=c.body.request_id.toUpperCase();c.body.actor_name=' '+c.body.actor_name+' ';c.body.reason=' '+c.body.reason+' ';assert.deepEqual(parse(c),parse(f.command(operation)));});
 test(operation+' audit binds original principal, target, declaration and every actual payload field',async()=>{const c=parse(f.command(operation)),e=f.audit(c);assert.deepEqual(await audit(e,c,f.principal),f.receipt(c));for(const mutate of [e=>e.id='invalid',e=>e.event_no='WRONG',e=>e.entity_id='invalid',e=>e.entity_ref='OTHER',e=>e.actor_principal_id=f.entity,e=>e.declared_actor_name='OTHER',e=>e.detail='OTHER',e=>e.event_type='WRONG',e=>e.entity_type='WRONG',e=>e.action='WRONG',e=>e.payload.actor_source='REQUEST_DECLARED']){const bad=copy(e);mutate(bad);assert.equal(await audit(bad,c,f.principal),null);}for(const k of Object.keys(e.payload)){const bad=copy(e);bad.payload[k]=k==='snapshot_no'?'':'WRONG';assert.equal(await audit(bad,c,f.principal),null,k);}for(const k of Object.keys(c.body)){const changed=copy(c);changed.body[k]=changed.body[k]===null?'OTHER':changed.body[k]+'OTHER';assert.equal(await audit(e,changed,f.principal),null,k);}});
 test(operation+' receipt whitelists original fields and never infers current/pass/replayed',()=>{const c=parse(f.command(operation)),r=f.receipt(c);assert.deepEqual(project({...r,token:'private',current_status:'PASSED',replayed:true},c),r);for(const k of Object.keys(r.result))assert.equal(project({...r,result:{...r.result,[k]:k==='snapshot_no'?'':'INVALID'}},c),null,k);});
 test(operation+' confirmed controller sends frozen original bytes and is terminal after confirmation',async()=>{const c=parse(f.command(operation)),s=new Submission(review(c,true));let calls=0;await s.send(true,async(url,init)=>{calls++;assert.equal(url,'/auth/acceptance-correction');assert.deepEqual(JSON.parse(init.body),c);assert.equal(init.method,'POST');assert.equal(init.credentials,'same-origin');assert.equal(init.cache,'no-store');assert.equal(init.redirect,'error');assert.ok(init.signal);return Response.json(f.receipt(c));});assert.equal(s.state.phase,'confirmed');await s.send(true,async()=>{calls++;});await s.recover(true,async()=>{calls++;});assert.equal(calls,1);});
 test(operation+' lost reply freezes bytes; explicit recovery and retry preserve original request',async()=>{const c=parse(f.command(operation)),s=new Submission(review(c,true)),bodies=[];await s.send(true,async(url,init)=>{bodies.push(init.body);throw Error('lost');});assert.equal(s.state.phase,'unknown');await s.recover(true,async(url,init)=>{assert.equal(url,'/auth/acceptance-correction-receipt');bodies.push(init.body);return Response.json({error:'outcome_unknown'},{status:502});});await s.send(true,async(url,init)=>{bodies.push(init.body);return Response.json(f.receipt(c));});assert.equal(s.state.phase,'confirmed');assert.equal(new Set(bodies).size,1);});
 test(operation+' synchronous send/query interlock blocks duplicate operations',async()=>{const s=new Submission(review(parse(f.command(operation)),true));let calls=0,finish;const mock=async()=>{calls++;return new Promise(r=>finish=r);};const p=s.send(true,mock);await s.send(true,mock);await s.recover(true,mock);assert.equal(calls,1);finish(Response.json({error:'outcome_unknown'},{status:502}));await p;const q=s.recover(true,mock);await s.send(true,mock);assert.equal(calls,2);finish(Response.json(f.receipt(s.state.command)));await q;assert.equal(s.state.phase,'confirmed');});
 test(operation+' only exact boolean-confirmed canonical review is accepted',()=>{const r=review(parse(f.command(operation)),true);
 for(const patch of [{confirmed:false},{confirmed:'true'},{command:{...r.command,url:'https://evil'}},{command:{...r.command,body:{...r.command.body,reason:' '+r.command.body.reason}}}])assert.throws(()=>new Submission({...r,...patch}));});
 test(operation+' later disabled/auth/conflict denial cannot erase uncertain original write',async()=>{const s=new Submission(review(parse(f.command(operation)),true));await s.send(true,async()=>{throw Error('lost');});await s.send(false);assert.equal(s.state.phase,'unknown');for(const [status,error]of [[403,'submission_forbidden'],[409,'request_conflict'],[401,'session_required']]){await s.send(true,async()=>Response.json({error},{status}));assert.equal(s.state.phase,'unknown');}await s.recover(false);assert.equal(s.state.phase,'unknown');});
 test(operation+' malformed/oversized/wrong-status responses stay unknown without auto retry',async()=>{for(const reply of [()=>Response.json({}),()=>Response.json({},{status:201}),()=>Response.json({padding:'x'.repeat(16385)}),()=>new Response('{'),()=>new Response(new Uint8Array([255]),{headers:{'content-type':'application/json'}})]){const s=new Submission(review(parse(f.command(operation)),true));let calls=0;await s.send(true,async()=>{calls++;return reply();});assert.equal(s.state.phase,'unknown');assert.equal(calls,1);}});
}

