const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');
const change='a1234567-1234-1234-1234-123456789abc',release='b1234567-1234-1234-1234-123456789abc',snapshot='c1234567-1234-1234-1234-123456789abc',group='d1234567-1234-1234-1234-123456789abc';
const count={total:123,assigned:82,assignment_percent:67,passed:41};
const data={change_id:change,request_no:'SCR/1',release_id:release,snapshot_id:snapshot,basis:'Current definitions',release:{id:release,type:'STANDARD',version:'Original version'},snapshot:{id:snapshot,snapshot_no:'SNAP/1',number:4},candidate_count:321,gap_count:45,summary:{acceptance:count,change_points:count,issues:count,dvp:{total:201,executed:101,passed:81}}};
function load(file,api,localized,collections){const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;const m={exports:{}};new Function('require','module','exports',code)(name=>{if(name==='next/link')return ({href,children})=>React.createElement('a',{href},children);if(name.endsWith('/api'))return {apiGet:api};if(name.endsWith('/localized'))return localized??{Localized:({children})=>React.createElement(React.Fragment,null,children),LocalizedAttributes:({children})=>children};if(name.endsWith('/change-coverage-views'))return load('lib/change-coverage-views.ts');if(name.endsWith('/change-coverage-collections'))return collections;return require(name);},m,m.exports);return m.exports;}
function response(url){const p=new URL(url,'https://test.invalid');const kind=p.pathname.includes('/groups/')?p.pathname.split('/groups/')[1].split('/')[0]:p.pathname.endsWith('/assignments')?'acceptance':undefined;return {...data,kind,group_id:group,id:group,ref:'Original ref',description:'Original notes',verification:'FAILED',item_count:120,excluded_link_count:3,assignment_count:122,total:123,next_offset:1,items:[{id:group,ref:'Original ref',description:'Original notes',verification:'FAILED',item_count:120,excluded_link_count:3,type:'STANDARD',version:'Original version',status:'OPEN',code:'DVP_ASSIGNMENT_MISSING',message:'No DVP assignment within this SCR.',owner_id:group,item_no:'Same item',title:'Original test title',scope:'SOFTWARE_TEST',declared_status:'COMPLETED',execution_no:9,result:'FAIL',actual_result:'Original observation',executed_at:'2026-10-04',dvp_item_id:'test-uuid',actor_name:'Declared reviewer name',reason:'Original reason',created_at:'Original time'}]};}
async function render(search={},transform=x=>x,localized){const calls=[];const Component=load('components/change-coverage-collections.tsx',async url=>{calls.push(url);return transform(response(url),url);},localized).default;return {calls,element:await Component({data,search})};}
const html=x=>renderToStaticMarkup(x.element);const links=x=>[...html(x).matchAll(/href="([^"]+)"/g)].map(m=>m[1].replaceAll('&amp;','&'));
test('assignment history retains exact predecessor/successor audits and original DVP without submission controls',async()=>{
 const old='e1234567-1234-1234-1234-123456789abc',next='f1234567-1234-1234-1234-123456789abc';
 const x=await render({group_kind:'acceptance',group_id:group},(r,url)=>url.includes('/assignments?')?{...r,items:r.items.map(i=>({...i,action:'SUPERSEDE',supersedes_id:old,superseded_by_id:next,effective:false,reason:'<script>stored reason</script>'}))}:r);
 for(const id of [old,next,group])assert.ok(links(x).includes('/activity/EVT-AC-'+id));
 assert.ok(html(x).includes('Historical assignment only'));assert.ok(html(x).includes('&lt;script&gt;stored reason&lt;/script&gt;'));
 assert.ok(!html(x).includes('<script>stored reason'));assert.ok(links(x).includes('/testing/dvp/test-uuid'));
 assert.ok(!html(x).includes('type="submit"'));assert.ok(html(x).includes('122'));
});
test('actual bilingual assignment history preserves raw identifiers and localizes actions/validity',async()=>{
 const tmp=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'slc-ac-history-'));
 try {
  require('node:child_process').execFileSync(process.execPath,[require.resolve('typescript/bin/tsc'),'components/localized.tsx','--target','ES2021','--module','commonjs','--jsx','react-jsx','--esModuleInterop','--resolveJsonModule','--strict','--skipLibCheck','--outDir',tmp]);
  fs.symlinkSync(path.resolve('node_modules'),path.join(tmp,'node_modules'),'dir');const localized=require(path.join(tmp,'components/localized.js'));
  for(const locale of ['zh','en'])for(const action of ['ASSIGN','SUPERSEDE','WITHDRAW']) {
   const x=await render({group_kind:'acceptance',group_id:group},(r,url)=>url.includes('/assignments?')?{...r,items:r.items.map(i=>({...i,action,supersedes_id:release,effective:action!=='WITHDRAW'}))}:r,localized);
   const output=renderToStaticMarkup(React.createElement(localized.LanguageProvider,{initialLocale:locale},x.element));
   assert.ok(output.includes(locale==='zh'?({ASSIGN:'分配',SUPERSEDE:'替代',WITHDRAW:'撤销'}[action]):action));
   assert.ok(output.includes(locale==='zh'?(action==='WITHDRAW'?'仅保留历史分配':'有效分配'):(action==='WITHDRAW'?'Historical assignment only':'Effective assignment')));
   assert.ok(output.includes(release)&&output.includes('Original reason')&&output.includes('test-uuid'));
  }
 }finally{fs.rmSync(tmp,{recursive:true,force:true});}
});
test('six bounded collections retain full counts with exact execution pins; no nested preload',async()=>{const x=await render();assert.equal(x.calls.length,6);for(const url of x.calls){const q=new URL(url,'https://test.invalid').searchParams;assert.equal(q.get('change_id'),change);assert.equal(q.get('release_id'),release);assert.equal(q.get('snapshot_id'),snapshot);assert.ok(url.includes('/change-coverage-views/'));}for(const n of [321,45,123,201])assert.ok(html(x).includes(n));assert.ok(html(x).includes('Select a coverage row'));assert.ok(html(x).includes('Original observation')&&html(x).includes('Original test title'));});
test('criterion selection loads exact summary/items/assignments and exact preparation target',async()=>{const x=await render({group_kind:'acceptance',group_id:group});assert.equal(x.calls.length,9);assert.ok(x.calls.some(u=>u.includes('/groups/acceptance/'+group+'/items')));assert.ok(x.calls.some(u=>u.includes('/acceptance/'+group+'/assignments')));assert.ok(html(x).includes('Original reason')&&html(x).includes('Declared reviewer name'));assert.ok(links(x).includes('/testing/dvp/test-uuid'));assert.ok(links(x).some(u=>u.includes('criterion='+group)&&u.includes('target=SCR%2F1')));});
test('independent first/next cursors keep frozen pins and unrelated selection',async()=>{const keys=['candidates_offset','gaps_offset','acceptance_offset','coverage_points_offset','coverage_issues_offset','coverage_items_offset','group_items_offset','assignments_offset'];const search={group_kind:'acceptance',group_id:group,coverage_limit:'1',...Object.fromEntries(keys.map((k,i)=>[k,String(i+20)]))};const x=await render(search);for(const key of keys){const next=links(x).find(l=>new URL(l,'https://test.invalid').searchParams.get(key)==='1');assert.ok(next);const q=new URL(next,'https://test.invalid').searchParams;assert.equal(q.get('snapshot_id'),snapshot);assert.equal(q.get('release_id'),release);for(const [k,v] of Object.entries(search))assert.equal(q.get(k),k===key?'1':v);const first=links(x).find(l=>l.includes('snapshot_id=')&&!new URL(l,'https://test.invalid').searchParams.has(key));assert.ok(first);}});
test('new group resets own child cursors only; release choice starts fresh context',async()=>{const x=await render({group_items_offset:'8',assignments_offset:'9',gaps_offset:'10'});const inspect=links(x).find(u=>u.includes('group_kind=points'));const q=new URL(inspect,'https://test.invalid').searchParams;assert.equal(q.get('group_items_offset'),null);assert.equal(q.get('assignments_offset'),null);assert.equal(q.get('gaps_offset'),'10');assert.equal(q.get('snapshot_id'),snapshot);const candidate=links(x).find(u=>u==='/changes/SCR%2F1/coverage?release_id='+group);assert.ok(candidate);});
test('unavailable/wrong child pins preserve complete parent counts independently',async()=>{for(const transform of [(r,u)=>u.includes('/gaps?')?null:r,(r,u)=>u.includes('/gaps?')?{...r,snapshot_id:'foreign'}:r,(r,u)=>u.includes('/groups/points?')?{...r,kind:'issues'}:r]){const x=await render({},transform);assert.equal(html(x).split('Coverage collection page unavailable.').length-1,1);assert.ok(html(x).includes('45')&&html(x).includes('Original notes'));}});
test('wrong selected summary stops nested reads; wrong items do not fabricate zero',async()=>{const x=await render({group_kind:'acceptance',group_id:group},(r,u)=>u.includes('/summary?')?{...r,group_id:'foreign'}:r);assert.equal(x.calls.length,7);assert.ok(html(x).includes('Selected coverage group unavailable.'));const wrong=await render({group_kind:'acceptance',group_id:group},(r,u)=>u.includes('/'+group+'/items?')?{...r,snapshot_id:'foreign'}:r);assert.ok(html(wrong).includes('120')&&html(wrong).includes('Coverage collection page unavailable.'));});
test('beyond-end and repeated pagination retain totals and forward invalid',async()=>{const x=await render({coverage_limit:['1','2'],gaps_offset:['0','1']},r=>({...r,items:[],next_offset:null}));assert.ok(html(x).includes('321')&&html(x).includes('No records on this page.'));assert.ok(!html(x).includes('Next page'));assert.equal(new URL(x.calls[0],'https://test.invalid').searchParams.get('limit'),'invalid');assert.equal(new URL(x.calls[1],'https://test.invalid').searchParams.get('offset'),'invalid');});
async function parent(search={},result=data){let props;const calls=[];const Page=load('app/changes/[id]/coverage/page.tsx',async url=>{calls.push(url);return result;},undefined,p=>{props=p;return React.createElement('span',null,'bounded-collections');}).default;return {calls,props:()=>props,output:renderToStaticMarkup(await Page({params:Promise.resolve({id:data.request_no}),searchParams:Promise.resolve(search)}))};}
test('parent passes full counts and explicit pins; empty form selects assignments only',async()=>{const x=await parent({release_id:release,snapshot_id:snapshot});assert.equal(x.props().data.change_id,change);assert.ok(x.output.includes('201')&&x.output.includes(snapshot));assert.ok(!x.output.includes('Only the first 100'));const empty=await parent({release_id:'',snapshot_no:''},{...data,release_id:'none',snapshot_id:'none',release:null,snapshot:null});assert.equal(empty.calls[0],'/api/v1/change-coverage-views/SCR%2F1/summary?');assert.ok(empty.props());});
test('missing/foreign summary or repeat context stops collections',async()=>{for(const result of [null,{...data,request_no:'foreign'},{...data,release:{id:'foreign'}},{...data,snapshot_id:'foreign'}]){const x=await parent({release_id:release,snapshot_id:snapshot},result);assert.equal(x.props(),undefined);assert.ok(x.output.includes('Coverage report unavailable'));}const repeated=await parent({release_id:['a','b']});assert.ok(repeated.calls[0].includes('release_id=invalid'));assert.equal(repeated.props(),undefined);});
test('actual Chinese and English SSR preserves original observations and pins',async()=>{const {execFileSync}=require('node:child_process');const tmp=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'slc-cov-views-'));try{execFileSync(process.execPath,[require.resolve('typescript/bin/tsc'),'components/localized.tsx','--target','ES2021','--module','commonjs','--jsx','react-jsx','--esModuleInterop','--resolveJsonModule','--strict','--skipLibCheck','--outDir',tmp]);fs.symlinkSync(path.resolve('node_modules'),path.join(tmp,'node_modules'),'dir');const localized=require(path.join(tmp,'components/localized.js'));for(const locale of ['zh','en']){const x=await render({group_kind:'acceptance',group_id:group},x=>x,localized);const output=renderToStaticMarkup(React.createElement(localized.LanguageProvider,{initialLocale:locale},x.element));assert.ok(output.includes(locale==='zh'?'分页覆盖证据':'Paged coverage evidence'));assert.ok(output.includes('Original observation')&&output.includes('Original reason')&&output.includes('Declared reviewer name'));assert.ok(output.includes(snapshot)&&output.includes(group));}}finally{fs.rmSync(tmp,{recursive:true,force:true});}});
