const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const ts=require('typescript');
const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');
const change={id:'a1234567-1234-1234-1234-123456789abc',request_no:'SCR A/1',title:'Original title',status:'OPEN',scope:'STANDARD',change_type:'FIX',source:'INTERNAL',criterion_count:123,issue_count:22,point_count:45,plan_count:67,point_item_count:88,plan_item_count:99};
const point='b1234567-1234-1234-1234-123456789abc',plan='c1234567-1234-1234-1234-123456789abc';
function load(file,api,localized,collections){
 const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;const m={exports:{}};
 new Function('require','module','exports',code)(name=>{
  if(name==='next/link')return ({href,children})=>React.createElement('a',{href},children);
  if(name.endsWith('/api'))return {apiGet:api};
  if(name.endsWith('/localized'))return localized??{Localized:({children})=>React.createElement(React.Fragment,null,children)};
  if(name.endsWith('/change-collections'))return collections;
  return require(name);
 },m,m.exports);return m.exports.default;
}
function response(url){const p=new URL(url,'https://test.invalid');const items=p.pathname.endsWith('/items');return {change_id:change.id,request_no:change.request_no,total:123,next_offset:1,point_id:point,plan_id:plan,items:[{id:items?'item-exact':p.pathname.endsWith('/plans')?plan:point,criterion_no:'AC1',issue_no:'Issue/1',change_no:'CP1',plan_no:'PLAN1',item_no:'DVP1',title:'Original title',description:'Original notes',status:'OPEN',item_count:120,relation_type:'RELATED'}]};}
async function render(search={},transform=x=>x,localized){const calls=[];const Component=load('components/change-collections.tsx',async url=>{calls.push(url);return transform(response(url),url);},localized);return {calls,element:await Component({change,search})};}
const html=x=>renderToStaticMarkup(x.element);
const links=x=>[...html(x).matchAll(/href="([^"]+)"/g)].map(m=>m[1].replaceAll('&amp;','&'));
test('four bounded parents and full counts; no selected-child bulk fallback',async()=>{const x=await render();assert.equal(x.calls.length,4);assert.ok(x.calls.every(u=>u.includes('/change-views/')&&u.includes('change_id='+change.id)));for(const n of [123,22,45,67,88,99])assert.ok(html(x).includes(n));assert.ok(html(x).includes('Select a change point')&&html(x).includes('Select a DVP plan'));assert.ok(links(x).includes('/issues/Issue%2F1'));});
test('selected UUID items, exact links and independently preserved cursors',async()=>{const search={scr_limit:'1',criteria_offset:'3',issues_offset:'4',points_offset:'5',plans_offset:'6',point_items_offset:'7',plan_items_offset:'8',point_id:point,plan_id:plan};const x=await render(search);assert.equal(x.calls.length,6);assert.ok(links(x).includes('/testing/dvp/item-exact'));for(const [i,key] of ['criteria_offset','issues_offset','points_offset','plans_offset','point_items_offset','plan_items_offset'].entries()){assert.equal(new URL(x.calls[i],'https://test.invalid').searchParams.get('offset'),search[key]);const next=links(x).find(l=>new URL(l,'https://test.invalid').searchParams.get(key)==='1');assert.ok(next);const q=new URL(next,'https://test.invalid').searchParams;for(const [k,v] of Object.entries(search))assert.equal(q.get(k),k===key?'1':v);const first=links(x).find(l=>l.startsWith('/changes/')&&!new URL(l,'https://test.invalid').searchParams.has(key));assert.ok(first);}});
test('selection links reset only own child offset',async()=>{const x=await render({point_items_offset:'9',plan_items_offset:'8',criteria_offset:'3',plan_id:plan});const select=links(x).find(l=>l.includes('point_id='+point));const q=new URL(select,'https://test.invalid').searchParams;assert.equal(q.get('point_items_offset'),null);assert.equal(q.get('plan_items_offset'),'8');assert.equal(q.get('criteria_offset'),'3');assert.equal(q.get('plan_id'),plan);});
test('wrong binding and unavailable isolated from full summary totals',async()=>{for(const transform of [(r,u)=>u.includes('/criteria?')?null:r,(r,u)=>u.includes('/criteria?')?{...r,change_id:'wrong'}:r,(r,u)=>u.includes('/points/'+point)?{...r,point_id:plan}:r]){const x=await render({point_id:point},transform);assert.equal(html(x).split('SCR collection page unavailable.').length-1,1);assert.ok(html(x).includes('123')&&html(x).includes('Original notes'));}});
test('beyond-end count and repeated raw parameters never reset silently',async()=>{const x=await render({scr_limit:['1','2'],criteria_offset:['3','4'],point_id:['a','b']},r=>({...r,items:[],next_offset:null}));assert.ok(html(x).includes('123')&&html(x).includes('No records on this page.'));assert.ok(!html(x).includes('Next page'));assert.equal(new URL(x.calls[0],'https://test.invalid').searchParams.get('limit'),'invalid');assert.equal(new URL(x.calls[0],'https://test.invalid').searchParams.get('offset'),'invalid');assert.ok(x.calls.some(u=>u.includes('/points/invalid/items')));});
test('summary unavailable/mismatched identity prevents child rendering',async()=>{for(const result of [null,{...change,request_no:'other'}]){let child=false;const Page=load('app/changes/[id]/page.tsx',async()=>result,undefined,()=>{child=true;return null;});const output=renderToStaticMarkup(await Page({params:Promise.resolve({id:change.request_no}),searchParams:Promise.resolve({})}));assert.ok(output.includes('Change request unavailable'));assert.equal(child,false);}});
test('parent passes exact identity, metadata and query to bounded collections',async()=>{let props;const Page=load('app/changes/[id]/page.tsx',async url=>{assert.equal(url,'/api/v1/change-views/SCR%20A%2F1/summary');return change;},undefined,p=>{props=p;return React.createElement('span',null,'collections');});const output=renderToStaticMarkup(await Page({params:Promise.resolve({id:change.request_no}),searchParams:Promise.resolve({criteria_offset:'3'})}));assert.equal(props.change.id,change.id);assert.equal(props.search.criteria_offset,'3');assert.ok(output.includes('entity_id='+change.id)&&output.includes('/changes/SCR%20A%2F1/coverage'));});
test('actual Chinese/English SSR labels with original content',async()=>{const {execFileSync}=require('node:child_process');const tmp=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'slc-change-views-'));try{execFileSync(process.execPath,[require.resolve('typescript/bin/tsc'),'components/localized.tsx','--target','ES2021','--module','commonjs','--jsx','react-jsx','--esModuleInterop','--resolveJsonModule','--strict','--skipLibCheck','--outDir',tmp]);fs.symlinkSync(path.resolve('node_modules'),path.join(tmp,'node_modules'),'dir');const localized=require(path.join(tmp,'components/localized.js'));for(const locale of ['zh','en']){const x=await render({},x=>x,localized);const output=renderToStaticMarkup(React.createElement(localized.LanguageProvider,{initialLocale:locale},x.element));assert.ok(output.includes(locale==='zh'?'变更请求完整计数':'Complete SCR counts'));assert.ok(output.includes('Original notes')&&output.includes('Original title'));assert.ok(output.includes(locale==='zh'?'查看 DVP 测试项':'View DVP items'));}}finally{fs.rmSync(tmp,{recursive:true,force:true});}});
