const {test,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const output=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'slc-resource-'));
require('node:child_process').execFileSync(process.execPath,[require.resolve('typescript/bin/tsc'),'lib/resource-command-transport.ts','lib/resource-command-audit.ts','--target','ES2021','--module','commonjs','--strict','--skipLibCheck','--outDir',output]);
const {parseResourceCommand:parse,resourceReview:review,resourceDigest:digest,projectResourceReceipt:project,ResourceSubmission:Submission}=require(path.join(output,'resource-command-transport.js'));
const {projectResourceAudit:audit}=require(path.join(output,'resource-command-audit.js'));
const f=require('./fixtures/resource-command.cjs'),copy=v=>JSON.parse(JSON.stringify(v));
after(()=>fs.rmSync(output,{recursive:true,force:true}));
test('canonical normalized Resource body and fixed path are frozen',()=>{const c=parse(f.command());assert.ok(Object.isFrozen(c.body));assert.equal(review(c).draft.path,'/api/v1/resources');assert.equal(review(c).draft.audit,'/activity/'+f.eventNo(c));assert.deepEqual(c.body,f.command().body);});
test('strict operation/target/body reject credential injection and malformed locations',()=>{
 const c=f.command();for(const value of [null,{...c,url:'https://evil'},{...c,operation:'impact'},{...c,target:f.key},{...c,body:{...c.body,token:'private'}},
  {...c,body:{...c.body,request_id:'invalid'}},{...c,body:{...c.body,location:'https://user:secret@example.com'}},{...c,body:{...c.body,location:'https://example.com/%0A'}},
  {...c,body:{...c.body,description:null}},{...c,body:{...c.body,description:'中'.repeat(3000)}},{...c,body:{...c.body,title:'\ud800'}}])assert.equal(parse(value),null);
});
test('normalization matches backend trimming and UUID case without URL normalization',()=>{const c=f.command();c.target=c.target.toUpperCase();c.body.entity_id=c.target;c.body.title=' 原始标题 ';c.body.actor_name=' Declared operator ';assert.deepEqual(parse(c),parse(f.command()));});
for(const [kind,location]of [['WEB_URL','https://example.com/中文?q=1#part'],['LOCAL_PATH','C:\\报告\\结果.pdf'],['NETWORK_PATH','//server/share/报告.pdf']])test(kind+' request digest interoperates and never fetches resource location',async()=>{
 const c=parse({...f.command(),body:{...f.command().body,location_kind:kind,location}});assert.ok(c);assert.equal(await digest(c),f.audit(c).payload.request_sha256);assert.deepEqual(await audit(f.audit(c),c,f.principal),f.receipt(c));
});
test('actor-bound audit strictly confirms every original declaration and private request field',async()=>{
 const c=parse(f.command()),e=f.audit(c);assert.deepEqual(await audit(e,c,f.principal),f.receipt(c));
 for(const mutate of [e=>e.id='invalid',e=>e.event_no='WRONG',e=>e.entity_id=f.target,e=>e.entity_ref=f.target,e=>e.actor_principal_id=f.target,e=>e.declared_actor_name='OTHER',
  e=>e.event_type='WRONG',e=>e.entity_type='WRONG',e=>e.action='WRONG',e=>e.detail='OTHER',e=>e.payload.actor_source='LEGACY',e=>e.payload.target_type='ISSUE',
  e=>e.payload.target_id=f.key,e=>e.payload.location_kind='LOCAL_PATH',e=>e.payload.request_digest_version=2,e=>delete e.payload.request_sha256,e=>e.payload.target_ref='']){
  const bad=copy(e);mutate(bad);assert.equal(await audit(bad,c,f.principal),null);
 }
 for(const k of Object.keys(c.body)){const changed=copy(c);changed.body[k]+='OTHER';assert.equal(await audit(e,changed,f.principal),null,k);}
});
test('legacy audit remains unknown without current-object or fabricated fingerprint fallback',async()=>{const c=parse(f.command()),e=f.audit(c);delete e.payload.request_sha256;delete e.payload.request_digest_version;assert.equal(await audit(e,c,f.principal),null);});
test('receipt excludes arbitrary fields/current status and rejects every changed original field',()=>{const c=parse(f.command()),r=f.receipt(c);assert.deepEqual(project({...r,token:'private',current_status:'ACTIVE'},c),r);for(const k of Object.keys(c.body).filter(k=>k!=='request_id'))assert.equal(project({...r,result:{...r.result,[k]:'OTHER'}},c),null,k);});
test('only exact confirmed review can construct controller',()=>{const r=review(parse(f.command()));for(const patch of [{confirmed:false},{confirmed:'true'},{draft:{...r.draft,path:'https://evil'}},{draft:{...r.draft,trace:'/wrong'}},{draft:{...r.draft,audit:'/wrong'}},{draft:{...r.draft,payload:{...r.draft.payload,token:'private'}}}])assert.throws(()=>new Submission({...r,...patch}));});
test('lost response freezes bytes and only explicit original audit query/retry can recover',async()=>{const s=new Submission(review(parse(f.command()))),bodies=[];await s.send(true,async(url,init)=>{bodies.push(init.body);throw Error('lost');});assert.equal(s.state.phase,'unknown');await s.recover(true,async(url,init)=>{assert.equal(url,'/auth/resource-command-receipt');bodies.push(init.body);return Response.json({error:'outcome_unknown'},{status:502});});await s.send(true,async(url,init)=>{assert.equal(url,'/auth/resource-command');bodies.push(init.body);return Response.json(f.receipt(s.state.command));});assert.equal(s.state.phase,'confirmed');assert.equal(new Set(bodies).size,1);let calls=0;await s.send(true,async()=>{calls++;});assert.equal(calls,0);});
test('synchronous sending/checking interlock prevents double sends and concurrent recovery',async()=>{const s=new Submission(review(parse(f.command())));let calls=0,finish;const fetcher=async()=>{calls++;return new Promise(r=>finish=r);};const p=s.send(true,fetcher);await s.send(true,fetcher);await s.recover(true,fetcher);assert.equal(calls,1);finish(Response.json({error:'outcome_unknown'},{status:502}));await p;const q=s.recover(true,fetcher);await s.send(true,fetcher);await s.recover(true,fetcher);assert.equal(calls,2);finish(Response.json(f.receipt(s.state.command)));await q;assert.equal(s.state.phase,'confirmed');});
test('later disabled/scope/conflict denial cannot erase unknown original write',async()=>{const s=new Submission(review(parse(f.command())));await s.send(true,async()=>{throw Error('lost');});await s.send(false);assert.equal(s.state.phase,'unknown');for(const [status,error]of [[403,'submission_forbidden'],[409,'request_conflict']]){await s.send(true,async()=>Response.json({error},{status}));assert.equal(s.state.phase,'unknown');}await s.recover(true,async()=>Response.json({error:'session_required'},{status:401}));assert.equal(s.state.phase,'unknown');});
test('oversized malformed and unexpected responses stay unknown without automatic retries',async()=>{for(const reply of [()=>Response.json({}),()=>Response.json({},{status:201}),()=>Response.json({padding:'x'.repeat(16385)}),()=>new Response('{'),()=>new Response(new Uint8Array([255]),{headers:{'content-type':'application/json'}})]){const s=new Submission(review(parse(f.command())));let calls=0;await s.send(true,async()=>{calls++;return reply();});assert.equal(s.state.phase,'unknown');assert.equal(calls,1);}});
