
import { Localized, LocalizedAttributes } from "../../../components/localized";
import Link from 'next/link';
import { apiGet } from '../../../lib/api';
import { safeWebLocation, type Resource } from '../../../lib/resources';
export default async function Page({ params }: { params: Promise<{ resourceId: string }> }) {
  const { resourceId } = await params;
  const row = await apiGet<Resource>(`/api/v1/resources/${encodeURIComponent(resourceId)}`);
  if (!row) return <section className="panel"><h1><Localized>{"Resource unavailable"}</Localized></h1><p className="muted"><Localized>{"The reference was not found or the API is unavailable."}</Localized></p><Link href="/resources"><Localized>{"Resource catalog →"}</Localized></Link></section>;
  const web = safeWebLocation(row);
  return <><div className="top"><div><div className="eyebrow"><Localized>{"APPEND-ONLY RESOURCE REFERENCE"}</Localized></div><h1><Localized>{row.title}</Localized></h1><p className="muted"><Localized>{row.description || 'No description recorded.'}</Localized></p></div></div><section className="panel"><h2><Localized>{"Business association"}</Localized></h2><p><Localized>{row.entity_type}</Localized><Localized>{" · "}</Localized><Link href={row.entity_href}><Localized>{row.entity_ref}</Localized></Link></p><p className="muted"><Localized>{"Object ID: "}</Localized><Localized>{row.entity_id}</Localized></p></section><section className="panel"><h2><Localized>{"Recorded location"}</Localized></h2><p><Localized>{row.location_kind}</Localized></p><code style={{overflowWrap:'anywhere'}}>{row.location}</code><Localized>{web && <p><a href={web} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer"><Localized>{"Open recorded web address ↗"}</Localized></a></p>}</Localized><p className="muted"><Localized>{"The system has not accessed or verified this location. Local and network paths must be opened on a computer with the appropriate access. No file upload or distribution permission is granted by this reference."}</Localized></p></section><section className="panel"><h2><Localized>{"Registration history"}</Localized></h2><div className="kv"><span><Localized>{"Declared actor"}</Localized></span><b><Localized>{row.actor_name}</Localized></b><span><Localized>{"Recorded at"}</Localized></span><b><Localized>{row.created_at}</Localized></b><span><Localized>{"Reason"}</Localized></span><b><Localized>{row.reason}</Localized></b></div><p className="muted"><Localized>{"Actor names are declarations until identity integration is implemented. This record cannot be edited or deleted."}</Localized></p></section><Link href={`/resources?entity_type=${row.entity_type}&entity_id=${row.entity_id}`}><Localized>{"Other resources for this object →"}</Localized></Link></>;
}
