
import { Localized, LocalizedAttributes } from "../../../components/localized";
import Link from 'next/link';
import { apiGet } from '../../../lib/api';

type Catalog = { total: number; status_counts: Record<string, number>; next_offset: number | null; items: { id: string; test_release_no: string; purpose_scope: string; status: string; snapshot_no: string; context_consistent: boolean; release: { id: string; type: string; version: string }; software: { code: string; name: string } }[] };

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const filters = await searchParams; const query = new URLSearchParams();
  for (const key of ['status', 'scope', 'release_id', 'q', 'offset']) if (filters[key]) query.set(key, filters[key]!);
  const data = await apiGet<Catalog>(`/api/v1/testing/releases?${query}`);
  const next = new URLSearchParams(query); if (data?.next_offset !== null && data?.next_offset !== undefined) next.set('offset', String(data.next_offset));
  const first = new URLSearchParams(query); first.delete('offset');
  return <>
    <div className="top"><div><div className="eyebrow"><Localized>{"PURPOSE-LIMITED SOFTWARE"}</Localized></div><h1><Localized>{"Test Releases"}</Localized></h1><p className="muted"><Localized>{"Frozen test software records. ACTIVE status does not authorize production, customer delivery or deployment."}</Localized></p></div><Link href="/testing/dvp"><Localized>{"DVP catalog →"}</Localized></Link></div>
    <p><Link href="/commands?operation=test-release"><Localized>{"Prepare test draft →"}</Localized></Link></p>
    <section className="panel"><form method="get" className="filters"><label><Localized>{"Status "}</Localized><LocalizedAttributes><input name="status" defaultValue={filters.status || ''} placeholder="ACTIVE / SUPERSEDED / DRAFT" maxLength={30} /></LocalizedAttributes></label><label><Localized>{"Purpose "}</Localized><select name="scope" defaultValue={filters.scope || ''}><option value=""><Localized>{"All purposes"}</Localized></option><option value="SOFTWARE_TEST"><Localized>{"Software Test"}</Localized></option><option value="BATTERY_TEST"><Localized>{"Battery Test"}</Localized></option><option value="CUSTOMER_TEST"><Localized>{"Customer Test"}</Localized></option></select></label><label><Localized>{"Search "}</Localized><LocalizedAttributes><input name="q" defaultValue={filters.q || ''} placeholder="Test release, version, snapshot or software" maxLength={200} /></LocalizedAttributes></label><Localized>{filters.release_id && <input type="hidden" name="release_id" value={filters.release_id} />}</Localized><button type="submit"><Localized>{"Filter"}</Localized></button><Link href="/testing/releases"><Localized>{"Reset"}</Localized></Link></form><p className="muted"><Localized>{"Public test environment is read-only. Controlled local API creation produces DRAFT records; activation and supersession workflows are pending."}</Localized></p></section>
    <Localized>{data ? <section className="panel tablewrap"><h2><Localized>{data.total}</Localized><Localized>{" matching test releases"}</Localized></h2><p className="muted"><Localized>{Object.entries(data.status_counts).map(([status, count]) => `${status}: ${count}`).join(' · ') || 'No status records'}</Localized><Localized>{" · Counts cover all filtered records."}</Localized></p><table><thead><tr><th><Localized>{"Test Release"}</Localized></th><th><Localized>{"Software / Version"}</Localized></th><th><Localized>{"Pinned Snapshot"}</Localized></th><th><Localized>{"Purpose"}</Localized></th><th><Localized>{"Status"}</Localized></th></tr></thead><tbody><Localized>{data.items.map(row => <tr key={row.id}><td><Link href={`/testing/releases/${encodeURIComponent(row.test_release_no)}`}><b><Localized>{row.test_release_no}</Localized></b></Link></td><td><Localized>{row.software.name}</Localized><div><Link href={`/releases/${row.release.type === 'APPLICATION' ? 'application' : 'standard'}/${row.release.id}`}><Localized>{row.release.type === 'APPLICATION' ? 'ASR' : 'SSR'}</Localized> <Localized>{row.release.version}</Localized></Link></div></td><td><Link href={`/snapshots/${encodeURIComponent(row.snapshot_no)}`}><Localized>{row.snapshot_no}</Localized></Link><Localized>{!row.context_consistent && <div className="muted"><Localized>{"Context mismatch; review record"}</Localized></div>}</Localized></td><td><Localized>{row.purpose_scope}</Localized></td><td><Localized>{row.status}</Localized></td></tr>)}</Localized></tbody></table><Localized>{!data.items.length && <p className="muted"><Localized>{"No matching test releases."}</Localized></p>}</Localized><p><Localized>{filters.offset && <Link href={`/testing/releases?${first}`}><Localized>{"First page"}</Localized></Link>}</Localized><Localized>{data.next_offset !== null && <Link href={`/testing/releases?${next}`}><Localized>{" Next page →"}</Localized></Link>}</Localized></p></section> : <section className="panel"><h2><Localized>{"Test release catalog unavailable"}</Localized></h2><p className="muted"><Localized>{"The API is unavailable or the filter is invalid."}</Localized></p></section>}</Localized>
  </>;
}
