import Link from 'next/link';
import { apiGet } from '../../../lib/api';

type Catalog = { total: number; status_counts: Record<string, number>; next_offset: number | null; items: { id: string; test_release_no: string; purpose_scope: string; status: string; snapshot_no: string; context_consistent: boolean; release: { id: string; type: string; version: string }; software: { code: string; name: string } }[] };

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const filters = await searchParams; const query = new URLSearchParams();
  for (const key of ['status', 'scope', 'release_id', 'q', 'offset']) if (filters[key]) query.set(key, filters[key]!);
  const data = await apiGet<Catalog>(`/api/v1/testing/releases?${query}`);
  const next = new URLSearchParams(query); if (data?.next_offset !== null && data?.next_offset !== undefined) next.set('offset', String(data.next_offset));
  const first = new URLSearchParams(query); first.delete('offset');
  return <>
    <div className="top"><div><div className="eyebrow">PURPOSE-LIMITED SOFTWARE</div><h1>Test Releases</h1><p className="muted">Frozen test software records. ACTIVE status does not authorize production, customer delivery or deployment.</p></div><Link href="/testing/dvp">DVP catalog →</Link></div>
    <p><Link href="/commands?operation=test-release">Prepare test draft →</Link></p>
    <section className="panel"><form method="get" className="filters"><label>Status <input name="status" defaultValue={filters.status || ''} placeholder="ACTIVE / SUPERSEDED / DRAFT" maxLength={30} /></label><label>Purpose <select name="scope" defaultValue={filters.scope || ''}><option value="">All purposes</option><option value="SOFTWARE_TEST">Software Test</option><option value="BATTERY_TEST">Battery Test</option><option value="CUSTOMER_TEST">Customer Test</option></select></label><label>Search <input name="q" defaultValue={filters.q || ''} placeholder="Test release, version, snapshot or software" maxLength={200} /></label>{filters.release_id && <input type="hidden" name="release_id" value={filters.release_id} />}<button type="submit">Filter</button><Link href="/testing/releases">Reset</Link></form><p className="muted">Public test environment is read-only. Controlled local API creation produces DRAFT records; activation and supersession workflows are pending.</p></section>
    {data ? <section className="panel tablewrap"><h2>{data.total} matching test releases</h2><p className="muted">{Object.entries(data.status_counts).map(([status, count]) => `${status}: ${count}`).join(' · ') || 'No status records'} · Counts cover all filtered records.</p><table><thead><tr><th>Test Release</th><th>Software / Version</th><th>Pinned Snapshot</th><th>Purpose</th><th>Status</th></tr></thead><tbody>{data.items.map(row => <tr key={row.id}><td><Link href={`/testing/releases/${encodeURIComponent(row.test_release_no)}`}><b>{row.test_release_no}</b></Link></td><td>{row.software.name}<div><Link href={`/releases/${row.release.type === 'APPLICATION' ? 'application' : 'standard'}/${row.release.id}`}>{row.release.type === 'APPLICATION' ? 'ASR' : 'SSR'} {row.release.version}</Link></div></td><td><Link href={`/snapshots/${encodeURIComponent(row.snapshot_no)}`}>{row.snapshot_no}</Link>{!row.context_consistent && <div className="muted">Context mismatch; review record</div>}</td><td>{row.purpose_scope}</td><td>{row.status}</td></tr>)}</tbody></table>{!data.items.length && <p className="muted">No matching test releases.</p>}<p>{filters.offset && <Link href={`/testing/releases?${first}`}>First page</Link>}{data.next_offset !== null && <Link href={`/testing/releases?${next}`}> Next page →</Link>}</p></section> : <section className="panel"><h2>Test release catalog unavailable</h2><p className="muted">The API is unavailable or the filter is invalid.</p></section>}
  </>;
}
