import { Localized } from '../../../../../components/localized';
import IssueCollections from '../../../../../components/issue-collections';
import Link from 'next/link';
import { apiGet } from '../../../../../lib/api';
import {rawIssue,type ImpactSummary,type IssueSearch} from '../../../../../lib/issue-views';
export default async function Page({params,searchParams}:{params:Promise<{id:string;releaseId:string}>;searchParams:Promise<IssueSearch>}) {
  const {id,releaseId}=await params;const search=await searchParams;const query=new URLSearchParams();const selected=rawIssue(search,'snapshot_id');if(selected!==undefined)query.set('snapshot_id',selected);
  const data=await apiGet<ImpactSummary>(`/api/v1/issue-views/${encodeURIComponent(id)}/impact/${encodeURIComponent(releaseId)}/summary?${query}`);
  if(!data||data.issue_no!==id||data.release_id.toLowerCase()!==releaseId.toLowerCase()||data.release.id!==data.release_id||(data.snapshot?.id||'none')!==data.snapshot_id||(selected!==undefined&&data.snapshot_id.toLowerCase()!==selected.toLowerCase()))return <section className="panel"><h1><Localized>{'Impact evidence unavailable'}</Localized></h1><p><Localized>{'The API is unavailable or this release is not a candidate for this issue.'}</Localized></p><Link href={`/issues/${encodeURIComponent(id)}/impact/${encodeURIComponent(releaseId)}`}><Localized>{'Reset impact review →'}</Localized></Link><p><Link href={`/issues/${encodeURIComponent(id)}`}><Localized>{'Back to issue →'}</Localized></Link></p></section>;
  return <Localized>
    <div className="top"><div><div className="eyebrow"><Localized>{'ISSUE #'}</Localized>{data.issue_no} · <Localized>{'IMPACT REVIEW'}</Localized></div><h1>{data.release.type==='APPLICATION'?'ASR':'SSR'} {data.release.version}</h1><p><Localized>{'Candidates share software with a linked SCR. Test results and manual judgments are separate evidence.'}</Localized></p></div><Link href={`/issues/${encodeURIComponent(id)}`}><Localized>{'Back to issue →'}</Localized></Link></div>
    <div className="grid2"><section className="panel"><h2><Localized>{'Selected frozen snapshot'}</Localized></h2><p><Localized>{'Release UUID: '}</Localized><code>{data.release_id}</code></p>{data.snapshot?<><Link href={`/snapshots/${encodeURIComponent(data.snapshot.snapshot_no)}`}>{data.snapshot.snapshot_no}</Link><p><Localized>{data.snapshot.status}</Localized> · {data.snapshot.number}</p><p><code>{data.snapshot.id}</code></p><p><code>{data.snapshot.content_hash}</code></p><Link href={`/commands?${new URLSearchParams({operation:'impact',target:data.issue_no,release:data.release_id,snapshot:data.snapshot_id})}`}><Localized>{'Prepare impact judgment for this frozen snapshot →'}</Localized></Link></>:<p><Localized>{'No snapshot recorded for this release.'}</Localized></p>}<p><Localized>{'Component evidence count'}</Localized>: {data.component_count} · <Localized>{'Linked DVP count'}</Localized>: {data.verification_count}</p><p><Link href={`/issues/${encodeURIComponent(id)}/impact/${releaseId}`}><Localized>{'Review latest frozen snapshot →'}</Localized></Link></p></section>
    <section className="panel"><h2><Localized>{'Latest judgment for this snapshot'}</Localized></h2>{data.assessment?<><b><Localized>{data.assessment.decision.replaceAll('_',' ')}</Localized></b><p><Localized>{data.assessment.reason}</Localized></p><p><Localized>{'Evidence reference: '}</Localized><Localized>{data.assessment.evidence_ref||'Not supplied'}</Localized></p><p><code>{data.assessment.id}</code></p><p><Localized>{'Declared reviewer'}</Localized>: {data.assessment.actor_name} · {data.assessment.created_at}</p></>:<p><Localized>{'No manual judgment recorded for this snapshot. Earlier snapshot judgments do not apply automatically.'}</Localized></p>}<p className="muted"><Localized>{'Public test access is read-only. A PASS result does not determine issue impact.'}</Localized></p></section></div>
    <p className="muted"><Localized>{'Execution evidence is pinned to the selected frozen snapshot; current Issue links and latest judgments remain live.'}</Localized></p>
    <IssueCollections data={data} search={search}/>
  </Localized>;
}
