import Link from 'next/link';
import { apiGet } from '../../../../../lib/api';

type Evidence = { issue_no: string; release: { id: string; type: string; version: string }; snapshot: { id: string; snapshot_no: string; status: string } | null; frozen_components: { code: string; version: string }[]; assessment: { decision: string; reason: string; evidence_ref: string | null; actor_name: string; created_at: string } | null; verification: { id: string; item_no: string; title: string; execution: { execution_no: number; result: string; actual_result: string | null; executed_at: string } | null }[] };

export default async function Page({ params }: { params: Promise<{ id: string; releaseId: string }> }) {
  const { id, releaseId } = await params;
  const data = await apiGet<Evidence>(`/api/v1/issues/${encodeURIComponent(id)}/impact/${encodeURIComponent(releaseId)}`);
  if (!data) return <section className="panel"><h1>Impact evidence unavailable</h1><p className="muted">The API is unavailable or this release is not a candidate for this issue.</p><Link href={`/issues/${encodeURIComponent(id)}`}>Back to issue →</Link></section>;
  return <>
    <div className="top"><div><div className="eyebrow">ISSUE #{data.issue_no} · IMPACT REVIEW</div><h1>{data.release.type === 'APPLICATION' ? 'ASR' : 'SSR'} {data.release.version}</h1><p className="muted">Candidates share software with a linked SCR. Test results and manual judgments are separate evidence.</p></div><Link href={`/issues/${encodeURIComponent(id)}`}>Back to issue →</Link></div>
    <div className="grid2"><section className="panel"><h2>Current snapshot</h2>{data.snapshot ? <><Link href={`/snapshots/${encodeURIComponent(data.snapshot.snapshot_no)}`}>{data.snapshot.snapshot_no}</Link><p>{data.snapshot.status}</p><ul>{data.frozen_components.map(c => <li key={`${c.code}:${c.version}`}>{c.code} · {c.version || 'Version not recorded'}</li>)}</ul>{!data.frozen_components.length && <p className="muted">No component evidence recorded.</p>}</> : <p className="muted">No snapshot recorded for this release.</p>}</section>
    <section className="panel"><h2>Latest judgment for this snapshot</h2>{data.assessment ? <><b>{data.assessment.decision.replaceAll('_', ' ')}</b><p>{data.assessment.reason}</p><p>Evidence reference: {data.assessment.evidence_ref || 'Not supplied'}</p><p className="muted">Declared reviewer: {data.assessment.actor_name} · {data.assessment.created_at}</p></> : <p className="muted">No manual judgment recorded for this snapshot. Earlier snapshot judgments do not apply automatically.</p>}<p className="muted">Reviewer names are supplied with the record; identity verification is pending. Public test access is read-only.</p></section></div>
    <section className="panel tablewrap"><h2>Linked DVP verification</h2><p className="muted">Only executions matching this release and its current snapshot are shown. A PASS result does not determine issue impact.</p><table><thead><tr><th>Item</th><th>Title</th><th>Latest execution</th><th>Result</th><th>Observation</th></tr></thead><tbody>{data.verification.map(item => <tr key={item.id}><td>{item.item_no}</td><td>{item.title}</td><td>{item.execution ? `#${item.execution.execution_no}` : 'No matching execution'}</td><td>{item.execution?.result || '—'}</td><td>{item.execution?.actual_result || '—'}</td></tr>)}</tbody></table>{!data.verification.length && <p className="muted">No DVP items linked to this issue.</p>}</section>
  </>;
}
