
import { Localized, LocalizedAttributes } from "../../../../../components/localized";
import Link from 'next/link';
import { apiGet } from '../../../../../lib/api';

type Evidence = { issue_no: string; release: { id: string; type: string; version: string }; snapshot: { id: string; snapshot_no: string; status: string } | null; frozen_components: { code: string; version: string }[]; assessment: { decision: string; reason: string; evidence_ref: string | null; actor_name: string; created_at: string } | null; verification: { id: string; item_no: string; title: string; execution: { execution_no: number; result: string; actual_result: string | null; executed_at: string } | null }[] };

export default async function Page({ params }: { params: Promise<{ id: string; releaseId: string }> }) {
  const { id, releaseId } = await params;
  const data = await apiGet<Evidence>(`/api/v1/issues/${encodeURIComponent(id)}/impact/${encodeURIComponent(releaseId)}`);
  if (!data) return <section className="panel"><h1><Localized>{"Impact evidence unavailable"}</Localized></h1><p className="muted"><Localized>{"The API is unavailable or this release is not a candidate for this issue."}</Localized></p><Link href={`/issues/${encodeURIComponent(id)}`}><Localized>{"Back to issue →"}</Localized></Link></section>;
  return <>
    <div className="top"><div><div className="eyebrow"><Localized>{"ISSUE #"}</Localized><Localized>{data.issue_no}</Localized><Localized>{" · IMPACT REVIEW"}</Localized></div><h1><Localized>{data.release.type === 'APPLICATION' ? 'ASR' : 'SSR'}</Localized> <Localized>{data.release.version}</Localized></h1><p className="muted"><Localized>{"Candidates share software with a linked SCR. Test results and manual judgments are separate evidence."}</Localized></p></div><Link href={`/issues/${encodeURIComponent(id)}`}><Localized>{"Back to issue →"}</Localized></Link></div>
    <div className="grid2"><section className="panel"><h2><Localized>{"Current snapshot"}</Localized></h2><Localized>{data.snapshot ? <><Link href={`/snapshots/${encodeURIComponent(data.snapshot.snapshot_no)}`}><Localized>{data.snapshot.snapshot_no}</Localized></Link><p><Localized>{data.snapshot.status}</Localized></p><p><Localized>{"Release UUID: "}</Localized><code>{data.release.id}</code></p><p><Localized>{"Snapshot UUID: "}</Localized><code>{data.snapshot.id}</code></p><Link href={`/commands?${new URLSearchParams({operation:"impact",target:data.issue_no,release:data.release.id,snapshot:data.snapshot.id})}`}><Localized>{"Prepare impact judgment for this frozen snapshot →"}</Localized></Link><ul><Localized>{data.frozen_components.map(c => <li key={`${c.code}:${c.version}`}><Localized>{c.code}</Localized><Localized>{" · "}</Localized><Localized>{c.version || 'Version not recorded'}</Localized></li>)}</Localized></ul><Localized>{!data.frozen_components.length && <p className="muted"><Localized>{"No component evidence recorded."}</Localized></p>}</Localized></> : <p className="muted"><Localized>{"No snapshot recorded for this release."}</Localized></p>}</Localized></section>
    <section className="panel"><h2><Localized>{"Latest judgment for this snapshot"}</Localized></h2><Localized>{data.assessment ? <><b><Localized>{data.assessment.decision.replaceAll('_', ' ')}</Localized></b><p><Localized>{data.assessment.reason}</Localized></p><p><Localized>{"Evidence reference: "}</Localized><Localized>{data.assessment.evidence_ref || 'Not supplied'}</Localized></p><p className="muted"><Localized>{"Declared reviewer: "}</Localized><Localized>{data.assessment.actor_name}</Localized><Localized>{" · "}</Localized><Localized>{data.assessment.created_at}</Localized></p></> : <p className="muted"><Localized>{"No manual judgment recorded for this snapshot. Earlier snapshot judgments do not apply automatically."}</Localized></p>}</Localized><p className="muted"><Localized>{"Reviewer names are supplied with the record; identity verification is pending. Public test access is read-only."}</Localized></p></section></div>
    <section className="panel tablewrap"><h2><Localized>{"Linked DVP verification"}</Localized></h2><p className="muted"><Localized>{"Only executions matching this release and its current snapshot are shown. A PASS result does not determine issue impact."}</Localized></p><table><thead><tr><th><Localized>{"Item"}</Localized></th><th><Localized>{"Title"}</Localized></th><th><Localized>{"Latest execution"}</Localized></th><th><Localized>{"Result"}</Localized></th><th><Localized>{"Observation"}</Localized></th></tr></thead><tbody><Localized>{data.verification.map(item => <tr key={item.id}><td><Localized>{item.item_no}</Localized></td><td><Localized>{item.title}</Localized></td><td><Localized>{item.execution ? `#${item.execution.execution_no}` : 'No matching execution'}</Localized></td><td><Localized>{item.execution?.result || '—'}</Localized></td><td><Localized>{item.execution?.actual_result || '—'}</Localized></td></tr>)}</Localized></tbody></table><Localized>{!data.verification.length && <p className="muted"><Localized>{"No DVP items linked to this issue."}</Localized></p>}</Localized></section>
  </>;
}
