import Link from 'next/link';
import { apiGet } from '../../../../lib/api';
import type { Execution } from '../../../../lib/dvp-types';

type Detail = { id: string; test_release_no: string; purpose_scope: string; status: string; context_consistent: boolean; is_latest_frozen_snapshot: boolean; notice: string; release: { id: string; type: string; version: string } | null; snapshot: { snapshot_no: string; number: number; status: string; content_hash: string } | null; artifacts: { id: string; component_code: string; component_version: string | null; filename: string; sha256: string; classification: string; distribution_level: string; ai_access_policy: string }[]; execution_summary: { records: number; matching_records: number; mismatched_records: number; executed_items: number; latest_result_counts: Record<string, number> } };
type Records = { total: number; next_offset: number | null; items: (Execution & { id: string; dvp_item_id: string; item_no: string; title: string; matches_test_context: boolean })[] };

export default async function Page({ params, searchParams }: { params: Promise<{ testReleaseNo: string }>; searchParams: Promise<{ offset?: string }> }) {
  const { testReleaseNo } = await params; const filters = await searchParams;
  const path = `/api/v1/testing/releases/${encodeURIComponent(testReleaseNo)}`;
  const [detail, records] = await Promise.all([apiGet<Detail>(path), apiGet<Records>(`${path}/executions?offset=${encodeURIComponent(filters.offset || '0')}`)]);
  if (!detail) return <section className="panel"><h1>Test release unavailable</h1><p className="muted">The record was not found or the API is unavailable.</p><Link href="/testing/releases">All test releases →</Link></section>;
  return <>
    <p><Link href={`/resources?entity_type=TEST_RELEASE&entity_id=${detail.id}`}>Materials & evidence references →</Link></p>
    <div className="top"><div><div className="eyebrow">TEST RELEASE · {detail.purpose_scope}</div><h1>{detail.test_release_no}</h1><p className="muted">{detail.notice}</p></div><span className="status">{detail.status}</span></div>
    <div className="grid2"><section className="panel"><h2>Pinned software context</h2>{detail.release && <p><Link href={`/releases/${detail.release.type === 'APPLICATION' ? 'application' : 'standard'}/${detail.release.id}`}>{detail.release.type === 'APPLICATION' ? 'ASR' : 'SSR'} {detail.release.version}</Link></p>}{detail.snapshot ? <><Link href={`/snapshots/${encodeURIComponent(detail.snapshot.snapshot_no)}`}>{detail.snapshot.snapshot_no}</Link><p>Freeze #{detail.snapshot.number} · {detail.snapshot.status}</p><code style={{overflowWrap:'anywhere'}}>{detail.snapshot.content_hash}</code></> : <p>Snapshot missing</p>}<p className="muted">{detail.is_latest_frozen_snapshot ? 'Pinned to the latest frozen snapshot of this release.' : 'Historical snapshot binding; a newer freeze does not replace this test record.'}</p>{!detail.context_consistent && <p className="muted">Stored release/snapshot context is inconsistent; review required.</p>}</section><section className="panel"><h2>Recorded execution summary</h2><p>{detail.execution_summary.records} records · {detail.execution_summary.executed_items} matching test items</p><p>{Object.entries(detail.execution_summary.latest_result_counts).map(([result, count]) => `${result}: ${count}`).join(' · ') || 'No matching execution results'}</p><p className="muted">Latest execution per item within this test release’s exact binding. Executed items do not represent a complete planned test set.</p>{detail.execution_summary.mismatched_records > 0 && <p className="muted">{detail.execution_summary.mismatched_records} records do not match this test release’s binding; excluded from the summary outcomes.</p>}</section></div>
    <section className="panel tablewrap"><h2>Frozen artifact manifest</h2><p className="muted">Policy metadata describes the pinned snapshot. Test purpose does not grant permission to distribute these files.</p><table><thead><tr><th>Component / Version</th><th>File / SHA-256</th><th>Classification</th><th>Distribution / AI Policy</th></tr></thead><tbody>{detail.artifacts.map(a => <tr key={a.id}><td>{a.component_code} · {a.component_version || '—'}</td><td>{a.filename}<div><code style={{overflowWrap:'anywhere'}}>{a.sha256}</code></div></td><td>{a.classification}</td><td>{a.distribution_level}<div>{a.ai_access_policy}</div></td></tr>)}</tbody></table>{!detail.artifacts.length && <p className="muted">No frozen artifacts recorded for this snapshot.</p>}</section>
    <section className="panel tablewrap"><h2>Linked execution records</h2>{records ? <><table><thead><tr><th>DVP / Execution</th><th>Result</th><th>Recorded Snapshot</th><th>Observation / Time</th></tr></thead><tbody>{records.items.map(e => <tr key={e.id}><td><Link href={`/testing/dvp/${e.dvp_item_id}`}>{e.item_no}</Link> · #{e.execution_no}</td><td>{e.result}{(!e.context_consistent || !e.matches_test_context) && <p className="muted">Context mismatch</p>}</td><td>{e.snapshot_no ? <Link href={`/snapshots/${encodeURIComponent(e.snapshot_no)}`}>{e.snapshot_no}</Link> : e.snapshot_id}</td><td>{e.actual_result || '—'}<div>{e.executed_at}</div></td></tr>)}</tbody></table>{!records.items.length && <p className="muted">No linked execution records.</p>}<p>{filters.offset && <Link href={`/testing/releases/${encodeURIComponent(testReleaseNo)}`}>First page</Link>}{records.next_offset !== null && <Link href={`/testing/releases/${encodeURIComponent(testReleaseNo)}?offset=${records.next_offset}`}> Next page →</Link>}</p></> : <p className="muted">Execution API unavailable.</p>}</section><Link href="/testing/releases">All test releases →</Link>
  </>;
}
