
import { Localized, LocalizedAttributes } from "../../../../components/localized";
import Link from 'next/link';
import { apiGet } from '../../../../lib/api';
import type { Execution } from '../../../../lib/dvp-types';

type Detail = { id: string; test_release_no: string; purpose_scope: string; status: string; context_consistent: boolean; is_latest_frozen_snapshot: boolean; notice: string; release: { id: string; type: string; version: string } | null; snapshot: { snapshot_no: string; number: number; status: string; content_hash: string } | null; artifacts: { id: string; component_code: string; component_version: string | null; filename: string; sha256: string; classification: string; distribution_level: string; ai_access_policy: string }[]; execution_summary: { records: number; matching_records: number; mismatched_records: number; executed_items: number; latest_result_counts: Record<string, number> } };
type Records = { total: number; next_offset: number | null; items: (Execution & { id: string; dvp_item_id: string; item_no: string; title: string; matches_test_context: boolean })[] };

export default async function Page({ params, searchParams }: { params: Promise<{ testReleaseNo: string }>; searchParams: Promise<{ offset?: string }> }) {
  const { testReleaseNo } = await params; const filters = await searchParams;
  const path = `/api/v1/testing/releases/${encodeURIComponent(testReleaseNo)}`;
  const [detail, records] = await Promise.all([apiGet<Detail>(path), apiGet<Records>(`${path}/executions?offset=${encodeURIComponent(filters.offset || '0')}`)]);
  if (!detail) return <section className="panel"><h1><Localized>{"Test release unavailable"}</Localized></h1><p className="muted"><Localized>{"The record was not found or the API is unavailable."}</Localized></p><Link href="/testing/releases"><Localized>{"All test releases →"}</Localized></Link></section>;
  return <>
    <p><Link href={`/resources?entity_type=TEST_RELEASE&entity_id=${detail.id}`}><Localized>{"Materials & evidence references →"}</Localized></Link></p>
    <div className="top"><div><div className="eyebrow"><Localized>{"TEST RELEASE · "}</Localized><Localized>{detail.purpose_scope}</Localized></div><h1><Localized>{detail.test_release_no}</Localized></h1><p className="muted"><Localized>{detail.notice}</Localized></p></div><span className="status"><Localized>{detail.status}</Localized></span></div>
    <div className="grid2"><section className="panel"><h2><Localized>{"Pinned software context"}</Localized></h2><Localized>{detail.release && <p><Link href={`/releases/${detail.release.type === 'APPLICATION' ? 'application' : 'standard'}/${detail.release.id}`}><Localized>{detail.release.type === 'APPLICATION' ? 'ASR' : 'SSR'}</Localized> <Localized>{detail.release.version}</Localized></Link></p>}</Localized><Localized>{detail.snapshot ? <><Link href={`/snapshots/${encodeURIComponent(detail.snapshot.snapshot_no)}`}><Localized>{detail.snapshot.snapshot_no}</Localized></Link><p><Localized>{"Freeze #"}</Localized><Localized>{detail.snapshot.number}</Localized><Localized>{" · "}</Localized><Localized>{detail.snapshot.status}</Localized></p><code style={{overflowWrap:'anywhere'}}>{detail.snapshot.content_hash}</code></> : <p><Localized>{"Snapshot missing"}</Localized></p>}</Localized><p className="muted"><Localized>{detail.is_latest_frozen_snapshot ? 'Pinned to the latest frozen snapshot of this release.' : 'Historical snapshot binding; a newer freeze does not replace this test record.'}</Localized></p><Localized>{!detail.context_consistent && <p className="muted"><Localized>{"Stored release/snapshot context is inconsistent; review required."}</Localized></p>}</Localized></section><section className="panel"><h2><Localized>{"Recorded execution summary"}</Localized></h2><p><Localized>{detail.execution_summary.records}</Localized><Localized>{" records · "}</Localized><Localized>{detail.execution_summary.executed_items}</Localized><Localized>{" matching test items"}</Localized></p><p><Localized>{Object.entries(detail.execution_summary.latest_result_counts).map(([result, count]) => `${result}: ${count}`).join(' · ') || 'No matching execution results'}</Localized></p><p className="muted"><Localized>{"Latest execution per item within this test release’s exact binding. Executed items do not represent a complete planned test set."}</Localized></p><Localized>{detail.execution_summary.mismatched_records > 0 && <p className="muted"><Localized>{detail.execution_summary.mismatched_records}</Localized><Localized>{" records do not match this test release’s binding; excluded from the summary outcomes."}</Localized></p>}</Localized></section></div>
    <section className="panel tablewrap"><h2><Localized>{"Frozen artifact manifest"}</Localized></h2><p className="muted"><Localized>{"Policy metadata describes the pinned snapshot. Test purpose does not grant permission to distribute these files."}</Localized></p><table><thead><tr><th><Localized>{"Component / Version"}</Localized></th><th><Localized>{"File / SHA-256"}</Localized></th><th><Localized>{"Classification"}</Localized></th><th><Localized>{"Distribution / AI Policy"}</Localized></th></tr></thead><tbody><Localized>{detail.artifacts.map(a => <tr key={a.id}><td><Localized>{a.component_code}</Localized><Localized>{" · "}</Localized><Localized>{a.component_version || '—'}</Localized></td><td><Localized>{a.filename}</Localized><div><code style={{overflowWrap:'anywhere'}}>{a.sha256}</code></div></td><td><Localized>{a.classification}</Localized></td><td><Localized>{a.distribution_level}</Localized><div><Localized>{a.ai_access_policy}</Localized></div></td></tr>)}</Localized></tbody></table><Localized>{!detail.artifacts.length && <p className="muted"><Localized>{"No frozen artifacts recorded for this snapshot."}</Localized></p>}</Localized></section>
    <section className="panel tablewrap"><h2><Localized>{"Linked execution records"}</Localized></h2><Localized>{records ? <><table><thead><tr><th><Localized>{"DVP / Execution"}</Localized></th><th><Localized>{"Result"}</Localized></th><th><Localized>{"Recorded Snapshot"}</Localized></th><th><Localized>{"Observation / Time"}</Localized></th></tr></thead><tbody><Localized>{records.items.map(e => <tr key={e.id}><td><Link href={`/testing/dvp/${e.dvp_item_id}`}><Localized>{e.item_no}</Localized></Link><Localized>{" · #"}</Localized><Localized>{e.execution_no}</Localized></td><td><Localized>{e.result}</Localized><Localized>{(!e.context_consistent || !e.matches_test_context) && <p className="muted"><Localized>{"Context mismatch"}</Localized></p>}</Localized></td><td><Localized>{e.snapshot_no ? <Link href={`/snapshots/${encodeURIComponent(e.snapshot_no)}`}><Localized>{e.snapshot_no}</Localized></Link> : e.snapshot_id}</Localized></td><td><Localized>{e.actual_result || '—'}</Localized><div><Localized>{e.executed_at}</Localized></div></td></tr>)}</Localized></tbody></table><Localized>{!records.items.length && <p className="muted"><Localized>{"No linked execution records."}</Localized></p>}</Localized><p><Localized>{filters.offset && <Link href={`/testing/releases/${encodeURIComponent(testReleaseNo)}`}><Localized>{"First page"}</Localized></Link>}</Localized><Localized>{records.next_offset !== null && <Link href={`/testing/releases/${encodeURIComponent(testReleaseNo)}?offset=${records.next_offset}`}><Localized>{" Next page →"}</Localized></Link>}</Localized></p></> : <p className="muted"><Localized>{"Execution API unavailable."}</Localized></p>}</Localized></section><Link href="/testing/releases"><Localized>{"All test releases →"}</Localized></Link>
  </>;
}
